import type { CityState, Shift } from "./models";

const BusinessShifts : Shift[] = [[7,16], [8, 17], [9, 18]];
const RetailShifts : Shift[] = [[6, 14], [11, 19], [16, 0]];
const ShiftWorkShifts : Shift[] = [[4,12], [12,20], [20,4]];

export const SeattleConfig : CityState = {
  config: {
      id: 'seattle',
      name: 'Seattle',
      gridWidth: 20,
      gridHeight: 20,
      tiles: [
        ['w', 'w', 'w', 'w', 'w', 'w', 'w', 'l', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w'],
        ['w', 'w', 'w', 'w', 'w', 'w', 'w', 'l', 'l', 'w', 'w', 'w', 'w', 'l', 'w', 'w', 'w', 'w', 'w', 'w'],
        ['l', 'w', 'w', 'w', 'l', 'l', 'l', 'l', 'l', 'l', 'w', 'w', 'l', 'l', 'l', 'l', 'l', 'l', 'w', 'w'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'w', 'w', 'w', 'l', 'l', 'l', 'l', 'l', 'l', 'w'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'w', 'l', 'l', 'l', 'l', 'w', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'w', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'w', 'l', 'l', 'w', 'w', 'l', 'l', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'w', 'w', 'w', 'w', 'w', 'l', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'w', 'w', 'w', 'w', 'l', 'l', 'w', 'l', 'l', 'w', 'w', 'w', 'w', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'w', 'w', 'l', 'l', 'l', 'w', 'w', 'l', 'l', 'l', 'w', 'w', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'w', 'w', 'w', 'w', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'w', 'w', 'l', 'l', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'w', 'w', 'w', 'w', 'w', 'w', 'l', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l'],
      ],
      neighborhoods: [
        {
          id: 'downtown',
          name: 'Downtown',
          position: { x: 5, y: 11 },
          icon: 'temaki-briefcase',
          color: '#e74c3c',
          residents: 39,
          proportionOfJobs: 410,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.2, // 20% of recreational trips
        },
        {
          id: 'capitol-hill',
          name: 'Capitol Hill',
          position: { x: 5, y: 10 },
          icon: 'home',
          color: '#2ecc71',
          residents: 38,
          proportionOfJobs: 168,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0, // No recreational demand
        },
        {
          id: 'needle',
          name: 'Needle',
          position: { x: 4, y: 10 },
          icon: 'museum',
          color: '#2ecc71',
          residents: 35,
          proportionOfJobs: 256,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0, // No recreational demand
        },
        {
          id: 'queen-anne',
          name: 'Queen Anne',
          position: { x: 4, y: 9 },
          icon: 'jewelry-store',
          color: '#2ecc71',
          residents: 22,
          proportionOfJobs: 35,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0, // No recreational demand
        },
        {
          id: 'west-queen-anne',
          name: 'West QA',
          position: { x: 3, y: 9 },
          icon: 'jewelry-store',
          color: '#2ecc71',
          residents: 17,
          proportionOfJobs: 21,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0, // No recreational demand
        },
        {
          id: 'industrial',
          name: 'Industrial',
          position: { x: 5, y: 14 },
          icon: 'construction',
          color: '#e74c3c',
          residents: 8,
          proportionOfJobs: 68,
          availableShifts: ShiftWorkShifts,
          proportionOfRecreationalDemand: 0.0, // 0% of recreational trips
        },
        {
          id: 'port',
          name: 'Port',
          position: { x: 4, y: 14 },
          icon: 'temaki-boat',
          color: '#e74c3c',
          residents: 9,
          proportionOfJobs: 70,
          availableShifts: ShiftWorkShifts,
          proportionOfRecreationalDemand: 0.0, // 0% of recreational trips
        },
        {
          id: 'georgetown',
          name: 'Georgetown',
          position: { x: 5, y: 15 },
          icon: 'beer',
          color: '#e74c3c',
          residents: 14,
          proportionOfJobs: 72,
          availableShifts: ShiftWorkShifts,
          proportionOfRecreationalDemand: 0.0, // 0% of recreational trips
        },
        {
          id: 'madison',
          name: 'Madison',
          position: { x: 6, y: 10 },
          icon: 'home',
          color: '#9b59b6',
          residents: 32,
          proportionOfJobs: 26,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'greenwood',
          name: 'Greenwood',
          position: { x: 4, y: 5 },
          icon: 'temaki-tree_needleleaved',
          color: '#2ecc71',
          residents: 24,
          proportionOfJobs: 12,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0, // No recreational demand
        },
        {
          id: 'licton-springs',
          name: 'Licton Springs',
          position: { x: 4, y: 4 },
          icon: 'hot-spring',
          color: '#2ecc71',
          residents: 22,
          proportionOfJobs: 18,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0, // No recreational demand
        },
        {
          id: 'tukwila',
          name: 'Tukwila',
          position: { x: 8, y: 19 },
          icon: 'bridge',
          color: '#e74c3c',
          residents: 9,
          proportionOfJobs: 62,
          availableShifts: ShiftWorkShifts,
          proportionOfRecreationalDemand: 0.0, // 0% of recreational trips
        },
        {
          id: 'bellevue',
          name: 'Bellevue',
          position: { x: 11, y: 10 },
          icon: 'gift',
          color: '#9b59b6',
          residents: 15,
          proportionOfJobs: 96,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'totem-lake',
          name: 'Totem Lake',
          position: { x: 12, y: 4 },
          icon: 'square',
          color: '#9b59b6',
          residents: 22,
          proportionOfJobs: 26,
          availableShifts: RetailShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'rose-hill',
          name: 'Rose Hill',
          position: { x: 12, y: 6 },
          icon: 'temaki-florist',
          color: '#9b59b6',
          residents: 16,
          proportionOfJobs: 13,
          availableShifts: RetailShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'redmond',
          name: 'Redmond',
          position: { x: 14, y: 6 },
          icon: 'city',
          color: '#9b59b6',
          residents: 16,
          proportionOfJobs: 24,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'redwest',
          name: 'RedWest',
          position: { x: 14, y: 7 },
          icon: 'bicycle',
          color: '#9b59b6',
          residents: 18,
          proportionOfJobs: 11,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'overlake',
          name: 'Overlake',
          position: { x: 14, y: 9 },
          icon: 'home',
          color: '#9b59b6',
          residents: 15,
          proportionOfJobs: 88,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'belred',
          name: 'BelRed',
          position: { x: 13, y: 9 },
          icon: 'home',
          color: '#9b59b6',
          residents: 18,
          proportionOfJobs: 112,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'lake-hills-west',
          name: 'Lake Hills West',
          position: { x: 13, y: 11 },
          icon: 'home',
          color: '#9b59b6',
          residents: 17,
          proportionOfJobs: 30,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'lake-hills-east',
          name: 'Lake Hills East',
          position: { x: 14, y: 11 },
          icon: 'home',
          color: '#9b59b6',
          residents: 16,
          proportionOfJobs: 16,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'sammammish',
          name: 'Sammammish',
          position: { x: 18, y: 10 },
          icon: 'home',
          color: '#9b59b6',
          residents: 16,
          proportionOfJobs: 4,
          availableShifts: RetailShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'juanita',
          name: 'Juanita',
          position: { x: 10, y: 4 },
          icon: 'home',
          color: '#9b59b6',
          residents: 15,
          proportionOfJobs: 10,
          availableShifts: RetailShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'north-juanita',
          name: 'North Juanita',
          position: { x: 10, y: 3 },
          icon: 'home',
          color: '#9b59b6',
          residents: 15,
          proportionOfJobs: 8,
          availableShifts: RetailShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'redmond-tech',
          name: 'Redmond Tech',
          position: { x: 14, y: 8 },
          icon: 'mobile-phone',
          color: '#9b59b6',
          residents: 6,
          proportionOfJobs: 82,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'stadium',
          name: 'Stadium',
          position: { x: 5, y: 12 },
          icon: 'baseball',
          color: '#e74c3c',
          residents: 9,
          proportionOfJobs: 55,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.3, // 30% of recreational trips
        },
        {
          id: 'central',
          name: 'Central',
          position: { x: 6, y: 11 },
          icon: 'circle',
          color: '#e74c3c',
          residents: 20,
          proportionOfJobs: 22,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'northgate',
          name: 'Northgate',
          position: { x: 5, y: 4 },
          icon: 'shop',
          color: '#3498db',
          residents: 15,
          proportionOfJobs: 16,
          availableShifts: RetailShifts,
          proportionOfRecreationalDemand: 0.4, // 40% of recreational trips
        },
        {
          id: 'maple-leaf',
          name: 'Maple Leaf',
          position: { x: 5, y: 5 },
          icon: 'home',
          color: '#3498db',
          residents: 16,
          proportionOfJobs: 8,
          availableShifts: RetailShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'roosevelt',
          name: 'Roosevelt',
          position: { x: 5, y: 6 },
          icon: 'home',
          color: '#3498db',
          residents: 17,
          proportionOfJobs: 8,
          availableShifts: RetailShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'u-village',
          name: 'U Village',
          position: { x: 7, y: 7 },
          icon: 'shop',
          color: '#3498db',
          residents: 8,
          proportionOfJobs: 38,
          availableShifts: RetailShifts,
          proportionOfRecreationalDemand: 0.3, // 30% of recreational trips
        },
        {
          id: 'ballard',
          name: 'Ballard',
          position: { x: 2, y: 6 },
          icon: 'home',
          color: '#f39c12',
          residents: 19,
          proportionOfJobs: 10,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'alaska-junction',
          name: 'Alaska Junction',
          position: { x: 2, y: 14 },
          icon: 'home',
          color: '#9b59b6',
          residents: 15,
          proportionOfJobs: 8,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'delridge',
          name: 'Delridge',
          position: { x: 3, y: 15 },
          icon: 'home',
          color: '#9b59b6',
          residents: 17,
          proportionOfJobs: 11,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'sealth',
          name: 'Sealth',
          position: { x: 3, y: 16 },
          icon: 'home',
          color: '#9b59b6',
          residents: 16,
          proportionOfJobs: 4,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'othello',
          name: 'Othello',
          position: { x: 7, y: 16 },
          icon: 'home',
          color: '#9b59b6',
          residents: 16,
          proportionOfJobs: 9,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'columbia-city',
          name: 'Columbia City',
          position: { x: 7, y: 15 },
          icon: 'home',
          color: '#9b59b6',
          residents: 17,
          proportionOfJobs: 5,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'fremont',
          name: 'Fremont',
          position: { x: 4, y: 8 },
          icon: 'home',
          color: '#2ecc71',
          residents: 17,
          proportionOfJobs: 12,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0, // No recreational demand
        },
        {
          id: 'wallingford',
          name: 'Wallingford',
          position: { x: 4, y: 7 },
          icon: 'home',
          color: '#2ecc71',
          residents: 17,
          proportionOfJobs: 17,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0, // No recreational demand
        },
        {
          id: 'frelard',
          name: 'Frelard',
          position: { x: 3, y: 7 },
          icon: 'home',
          color: '#2ecc71',
          residents: 18,
          proportionOfJobs: 20,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0, // No recreational demand
        },
        {
          id: 'ballard-market',
          name: 'Ballard Market',
          position: { x: 2, y: 7 },
          icon: 'home',
          color: '#2ecc71',
          residents: 16,
          proportionOfJobs: 18,
          availableShifts: RetailShifts,
          proportionOfRecreationalDemand: 0.0, // No recreational demand
        },
        {
          id: 'phinney-ridge',
          name: 'Phinney Ridge',
          position: { x: 3, y: 6 },
          icon: 'home',
          color: '#2ecc71',
          residents: 19,
          proportionOfJobs: 10,
          availableShifts: RetailShifts,
          proportionOfRecreationalDemand: 0.0, // No recreational demand
        },
        {
          id: 'crown-hill',
          name: 'Crown Hill',
          position: { x: 3, y: 5 },
          icon: 'home',
          color: '#2ecc71',
          residents: 16,
          proportionOfJobs: 6,
          availableShifts: RetailShifts,
          proportionOfRecreationalDemand: 0.0, // No recreational demand
        },
        {
          id: 'beacon-hill',
          name: 'Beacon Hill',
          position: { x: 6, y: 13 },
          icon: 'home',
          color: '#9b59b6',
          residents: 14,
          proportionOfJobs: 13,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'coal-creek',
          name: 'Coal Creek',
          position: { x: 12, y: 14 },
          icon: 'home',
          color: '#9b59b6',
          residents: 16,
          proportionOfJobs: 20,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
      ],
      initialPopulation: 100,
      populationGrowthRate: 0.05,
      initialBudget: 10000,
      budgetBaseline: 1000,
      budgetBonusPerHappyCitizen: 10,
      walkingSpeed: 0.05,
      trainSpeed: 0.15,
      timePerStationStop: 1,
      costPerStation: 1000,
      costPerTrackMileLand: 500,
      costPerTrackMileWater: 1000,
      costPerTrain: 2000,
      trainCapacity: 10,
    },
    currentMonth: 1,
    currentDay: 0,
    population: 45, // Initial: downtown (5) + commercial-a (10) + residential-1 (30) on day 0
    budget: 10000,
  };