import type { CityState, Shift } from "./models";

const BusinessShifts : Shift[] = [[7,16], [8, 17], [9, 18]];
const RetailShifts : Shift[] = [[7, 15], [11, 19], [15, 23]];
const ShiftWorkShifts : Shift[] = [[6,14], [14,22], [22,6]];

export const SeattleConfig : CityState = {
  config: {
      id: 'seattle',
      name: 'Seattle',
      gridWidth: 20,
      gridHeight: 20,
      tiles: [
        ['w', 'w', 'w', 'w', 'w', 'w', 'w', 'l', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w'],
        ['w', 'w', 'w', 'w', 'w', 'w', 'w', 'l', 'l', 'w', 'w', 'w', 'w', 'l', 'w', 'w', 'w', 'w', 'w', 'w'],
        ['l', 'w', 'w', 'w', 'l', 'l', 'l', 'l', 'l', 'l', 'w', 'w', 'l', 'l', 'l', 'l', 'l', 'l', 'w', 'w'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'w', 'w', 'w', 'l', 'l', 'l', 'l', 'l', 'l', 'w'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'w', 'l', 'l', 'l', 'l', 'w', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'w', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'w', 'l', 'l', 'w', 'w', 'l', 'l', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'w', 'w', 'w', 'w', 'w', 'l', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'w', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'w', 'w', 'w', 'w', 'l', 'l', 'w', 'l', 'l', 'w', 'w', 'w', 'w', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'w', 'w', 'l', 'l', 'l', 'w', 'w', 'l', 'l', 'l', 'w', 'w', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'w', 'w', 'w', 'w', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'w', 'w', 'l', 'l', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'w', 'w', 'w', 'w', 'w', 'w', 'l', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l'],
        ['l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l'],
      ],
      neighborhoods: [
        {
          id: 'downtown',
          name: 'Downtown',
          position: { x: 5, y: 11 },
          icon: 'temaki-briefcase',
          color: '#e74c3c',
          residents: 22,
          proportionOfJobs: 219,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.2, // 20% of recreational trips
        },
        {
          id: 'stadium',
          name: 'Stadium',
          position: { x: 5, y: 12 },
          icon: 'baseball',
          color: '#e74c3c',
          residents: 9,
          proportionOfJobs: 55,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.3, // 30% of recreational trips
        },
        {
          id: 'central',
          name: 'Central',
          position: { x: 6, y: 11 },
          icon: 'circle',
          color: '#e74c3c',
          residents: 20,
          proportionOfJobs: 22,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'industrial',
          name: 'Industrial',
          position: { x: 5, y: 13 },
          icon: 'construction',
          color: '#e74c3c',
          residents: 10,
          proportionOfJobs: 55,
          availableShifts: ShiftWorkShifts,
          proportionOfRecreationalDemand: 0.0, // 0% of recreational trips
        },
        {
          id: 'northgate',
          name: 'Northgate',
          position: { x: 5, y: 4 },
          icon: 'shop',
          color: '#3498db',
          residents: 15,
          proportionOfJobs: 16,
          availableShifts: RetailShifts,
          proportionOfRecreationalDemand: 0.4, // 40% of recreational trips
        },
        {
          id: 'u-village',
          name: 'U Village',
          position: { x: 7, y: 7 },
          icon: 'shop',
          color: '#3498db',
          residents: 8,
          proportionOfJobs: 38,
          availableShifts: RetailShifts,
          proportionOfRecreationalDemand: 0.3, // 30% of recreational trips
        },
        {
          id: 'capitol-hill',
          name: 'Capitol Hill',
          position: { x: 5, y: 10 },
          icon: 'home',
          color: '#2ecc71',
          residents: 38,
          proportionOfJobs: 168,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0, // No recreational demand
        },
        {
          id: 'ballard',
          name: 'Ballard',
          position: { x: 2, y: 6 },
          icon: 'home',
          color: '#f39c12',
          residents: 19,
          proportionOfJobs: 10,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'alaska-junction',
          name: 'Alaska Junction',
          position: { x: 2, y: 14 },
          icon: 'home',
          color: '#9b59b6',
          residents: 15,
          proportionOfJobs: 8,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'beacon-hill',
          name: 'Beacon Hill',
          position: { x: 6, y: 13 },
          icon: 'home',
          color: '#9b59b6',
          residents: 14,
          proportionOfJobs: 13,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'bellevue',
          name: 'Bellevue',
          position: { x: 11, y: 10 },
          icon: 'gift',
          color: '#9b59b6',
          residents: 15,
          proportionOfJobs: 96,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
        {
          id: 'redmond-tech',
          name: 'Redmond Tech',
          position: { x: 14, y: 8 },
          icon: 'mobile-phone',
          color: '#9b59b6',
          residents: 6,
          proportionOfJobs: 82,
          availableShifts: BusinessShifts,
          proportionOfRecreationalDemand: 0.0,
        },
      ],
      initialPopulation: 100,
      populationGrowthRate: 0.05,
      initialBudget: 30000,
      budgetBaseline: 1000,
      budgetBonusPerHappyCitizen: 10,
      walkingSpeed: 0.05,
      trainSpeed: 0.15,
      timePerStationStop: 1,
      costPerStation: 1000,
      costPerTrackMileLand: 500,
      costPerTrackMileWater: 1000,
      costPerTrain: 2000,
      trainCapacity: 10,
    },
    currentMonth: 1,
    currentDay: 0,
    population: 45, // Initial: downtown (5) + commercial-a (10) + residential-1 (30) on day 0
    budget: 30000,
  };