import { iconPaths } from "./iconPaths";

// Generated neighborhoods from GeoJSON
const neighborhoods = [
  {
    id: '5-9',
    name: '5-9',
    position: { x: 5, y: 9 },
    icon: Object.keys(iconPaths)[100+9 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 25231,
    proportionOfJobs: 57811,
    normalizedWorkers: 145680,
    prominence: 25231,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-9',
    name: '6-9',
    position: { x: 6, y: 9 },
    icon: Object.keys(iconPaths)[120+9 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 9505,
    proportionOfJobs: 5722,
    normalizedWorkers: 134016,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-9',
    name: '7-9',
    position: { x: 7, y: 9 },
    icon: Object.keys(iconPaths)[140+9 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2517,
    proportionOfJobs: 5525,
    normalizedWorkers: 121592,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-11',
    name: '5-11',
    position: { x: 5, y: 11 },
    icon: Object.keys(iconPaths)[100+11 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3236,
    proportionOfJobs: 2885,
    normalizedWorkers: 131107,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-12',
    name: '5-12',
    position: { x: 5, y: 12 },
    icon: Object.keys(iconPaths)[100+12 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 10348,
    proportionOfJobs: 7388,
    normalizedWorkers: 131299,
    prominence: 1475,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-13',
    name: '6-13',
    position: { x: 6, y: 13 },
    icon: Object.keys(iconPaths)[120+13 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 7220,
    proportionOfJobs: 6703,
    normalizedWorkers: 124662,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-14',
    name: '7-14',
    position: { x: 7, y: 14 },
    icon: Object.keys(iconPaths)[140+14 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4226,
    proportionOfJobs: 997,
    normalizedWorkers: 114861,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-7',
    name: '6-7',
    position: { x: 6, y: 7 },
    icon: Object.keys(iconPaths)[120+7 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3688,
    proportionOfJobs: 3754,
    normalizedWorkers: 119719,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-6',
    name: '6-6',
    position: { x: 6, y: 6 },
    icon: Object.keys(iconPaths)[120+6 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4872,
    proportionOfJobs: 6098,
    normalizedWorkers: 114151,
    prominence: 578,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-5',
    name: '7-5',
    position: { x: 7, y: 5 },
    icon: Object.keys(iconPaths)[140+5 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4294,
    proportionOfJobs: 3277,
    normalizedWorkers: 109044,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '8-4',
    name: '8-4',
    position: { x: 8, y: 4 },
    icon: Object.keys(iconPaths)[160+4 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2264,
    proportionOfJobs: 1043,
    normalizedWorkers: 101426,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-4',
    name: '10-4',
    position: { x: 10, y: 4 },
    icon: Object.keys(iconPaths)[200+4 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2028,
    proportionOfJobs: 435,
    normalizedWorkers: 95416,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-4',
    name: '12-4',
    position: { x: 12, y: 4 },
    icon: Object.keys(iconPaths)[240+4 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2855,
    proportionOfJobs: 1310,
    normalizedWorkers: 91716,
    prominence: 105,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-5',
    name: '13-5',
    position: { x: 13, y: 5 },
    icon: Object.keys(iconPaths)[260+5 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2332,
    proportionOfJobs: 791,
    normalizedWorkers: 91588,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-15',
    name: '7-15',
    position: { x: 7, y: 15 },
    icon: Object.keys(iconPaths)[140+15 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2377,
    proportionOfJobs: 311,
    normalizedWorkers: 109050,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-6',
    name: '13-6',
    position: { x: 13, y: 6 },
    icon: Object.keys(iconPaths)[260+6 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3067,
    proportionOfJobs: 15264,
    normalizedWorkers: 94263,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-7',
    name: '13-7',
    position: { x: 13, y: 7 },
    icon: Object.keys(iconPaths)[260+7 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1959,
    proportionOfJobs: 9682,
    normalizedWorkers: 96298,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-8',
    name: '13-8',
    position: { x: 13, y: 8 },
    icon: Object.keys(iconPaths)[260+8 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2912,
    proportionOfJobs: 748,
    normalizedWorkers: 99243,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '14-9',
    name: '14-9',
    position: { x: 14, y: 9 },
    icon: Object.keys(iconPaths)[280+9 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 5523,
    proportionOfJobs: 3719,
    normalizedWorkers: 97964,
    prominence: 2563,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '14-11',
    name: '14-11',
    position: { x: 14, y: 11 },
    icon: Object.keys(iconPaths)[280+11 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4351,
    proportionOfJobs: 81513,
    normalizedWorkers: 96908,
    prominence: 1527,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '14-12',
    name: '14-12',
    position: { x: 14, y: 12 },
    icon: Object.keys(iconPaths)[280+12 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2824,
    proportionOfJobs: 358,
    normalizedWorkers: 95512,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '14-13',
    name: '14-13',
    position: { x: 14, y: 13 },
    icon: Object.keys(iconPaths)[280+13 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3668,
    proportionOfJobs: 11465,
    normalizedWorkers: 95157,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-16',
    name: '6-16',
    position: { x: 6, y: 16 },
    icon: Object.keys(iconPaths)[120+16 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4666,
    proportionOfJobs: 1742,
    normalizedWorkers: 106919,
    prominence: 313,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-12',
    name: '4-12',
    position: { x: 4, y: 12 },
    icon: Object.keys(iconPaths)[80+12 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4696,
    proportionOfJobs: 2351,
    normalizedWorkers: 127710,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '14-14',
    name: '14-14',
    position: { x: 14, y: 14 },
    icon: Object.keys(iconPaths)[280+14 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 6074,
    proportionOfJobs: 7171,
    normalizedWorkers: 94279,
    prominence: 3759,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-4',
    name: '6-4',
    position: { x: 6, y: 4 },
    icon: Object.keys(iconPaths)[120+4 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4886,
    proportionOfJobs: 829,
    normalizedWorkers: 104173,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-4',
    name: '5-4',
    position: { x: 5, y: 4 },
    icon: Object.keys(iconPaths)[100+4 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1027,
    proportionOfJobs: 17963,
    normalizedWorkers: 100596,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-4',
    name: '4-4',
    position: { x: 4, y: 4 },
    icon: Object.keys(iconPaths)[80+4 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2671,
    proportionOfJobs: 1120,
    normalizedWorkers: 99149,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-12',
    name: '3-12',
    position: { x: 3, y: 12 },
    icon: Object.keys(iconPaths)[60+12 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 5003,
    proportionOfJobs: 6613,
    normalizedWorkers: 121049,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-17',
    name: '6-17',
    position: { x: 6, y: 17 },
    icon: Object.keys(iconPaths)[120+17 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1719,
    proportionOfJobs: 426,
    normalizedWorkers: 98559,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-9',
    name: '4-9',
    position: { x: 4, y: 9 },
    icon: Object.keys(iconPaths)[80+9 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 18180,
    proportionOfJobs: 104108,
    normalizedWorkers: 138018,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-13',
    name: '3-13',
    position: { x: 3, y: 13 },
    icon: Object.keys(iconPaths)[60+13 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4259,
    proportionOfJobs: 741,
    normalizedWorkers: 118362,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '14-16',
    name: '14-16',
    position: { x: 14, y: 16 },
    icon: Object.keys(iconPaths)[280+16 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3707,
    proportionOfJobs: 1280,
    normalizedWorkers: 85126,
    prominence: 545,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-3',
    name: '12-3',
    position: { x: 12, y: 3 },
    icon: Object.keys(iconPaths)[240+3 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2036,
    proportionOfJobs: 450,
    normalizedWorkers: 88207,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-3',
    name: '4-3',
    position: { x: 4, y: 3 },
    icon: Object.keys(iconPaths)[80+3 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3332,
    proportionOfJobs: 2427,
    normalizedWorkers: 95261,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '14-5',
    name: '14-5',
    position: { x: 14, y: 5 },
    icon: Object.keys(iconPaths)[280+5 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3845,
    proportionOfJobs: 644,
    normalizedWorkers: 88423,
    prominence: 1513,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-16',
    name: '13-16',
    position: { x: 13, y: 16 },
    icon: Object.keys(iconPaths)[260+16 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2858,
    proportionOfJobs: 2653,
    normalizedWorkers: 89318,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-16',
    name: '12-16',
    position: { x: 12, y: 16 },
    icon: Object.keys(iconPaths)[240+16 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3577,
    proportionOfJobs: 9864,
    normalizedWorkers: 93558,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-2',
    name: '12-2',
    position: { x: 12, y: 2 },
    icon: Object.keys(iconPaths)[240+2 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2192,
    proportionOfJobs: 329,
    normalizedWorkers: 85005,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '15-5',
    name: '15-5',
    position: { x: 15, y: 5 },
    icon: Object.keys(iconPaths)[300+5 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3426,
    proportionOfJobs: 545,
    normalizedWorkers: 83833,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-17',
    name: '5-17',
    position: { x: 5, y: 17 },
    icon: Object.keys(iconPaths)[100+17 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3551,
    proportionOfJobs: 2220,
    normalizedWorkers: 99407,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-4',
    name: '3-4',
    position: { x: 3, y: 4 },
    icon: Object.keys(iconPaths)[60+4 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4200,
    proportionOfJobs: 1063,
    normalizedWorkers: 97019,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-14',
    name: '3-14',
    position: { x: 3, y: 14 },
    icon: Object.keys(iconPaths)[60+14 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 8824,
    proportionOfJobs: 2729,
    normalizedWorkers: 115564,
    prominence: 3115,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-2',
    name: '4-2',
    position: { x: 4, y: 2 },
    icon: Object.keys(iconPaths)[80+2 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2035,
    proportionOfJobs: 833,
    normalizedWorkers: 89457,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-17',
    name: '12-17',
    position: { x: 12, y: 17 },
    icon: Object.keys(iconPaths)[240+17 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2405,
    proportionOfJobs: 3344,
    normalizedWorkers: 88348,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '15-9',
    name: '15-9',
    position: { x: 15, y: 9 },
    icon: Object.keys(iconPaths)[300+9 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3684,
    proportionOfJobs: 1925,
    normalizedWorkers: 91711,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-1',
    name: '12-1',
    position: { x: 12, y: 1 },
    icon: Object.keys(iconPaths)[240+1 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4304,
    proportionOfJobs: 1373,
    normalizedWorkers: 81859,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-15',
    name: '11-15',
    position: { x: 11, y: 15 },
    icon: Object.keys(iconPaths)[220+15 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4913,
    proportionOfJobs: 4759,
    normalizedWorkers: 101139,
    prominence: 1679,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-5',
    name: '2-5',
    position: { x: 2, y: 5 },
    icon: Object.keys(iconPaths)[40+5 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 7437,
    proportionOfJobs: 6351,
    normalizedWorkers: 96805,
    prominence: 5535,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-18',
    name: '12-18',
    position: { x: 12, y: 18 },
    icon: Object.keys(iconPaths)[240+18 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2976,
    proportionOfJobs: 1578,
    normalizedWorkers: 83772,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-8',
    name: '12-8',
    position: { x: 12, y: 8 },
    icon: Object.keys(iconPaths)[240+8 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2211,
    proportionOfJobs: 14211,
    normalizedWorkers: 101737,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-9',
    name: '11-9',
    position: { x: 11, y: 9 },
    icon: Object.keys(iconPaths)[220+9 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 8365,
    proportionOfJobs: 59803,
    normalizedWorkers: 108546,
    prominence: 6092,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '8-3',
    name: '8-3',
    position: { x: 8, y: 3 },
    icon: Object.keys(iconPaths)[160+3 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2060,
    proportionOfJobs: 374,
    normalizedWorkers: 96416,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-17',
    name: '4-17',
    position: { x: 4, y: 17 },
    icon: Object.keys(iconPaths)[80+17 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4710,
    proportionOfJobs: 2464,
    normalizedWorkers: 97129,
    prominence: 919,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '8-2',
    name: '8-2',
    position: { x: 8, y: 2 },
    icon: Object.keys(iconPaths)[160+2 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1884,
    proportionOfJobs: 649,
    normalizedWorkers: 91118,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-14',
    name: '11-14',
    position: { x: 11, y: 14 },
    icon: Object.keys(iconPaths)[220+14 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4320,
    proportionOfJobs: 2795,
    normalizedWorkers: 103454,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '15-14',
    name: '15-14',
    position: { x: 15, y: 14 },
    icon: Object.keys(iconPaths)[300+14 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3305,
    proportionOfJobs: 705,
    normalizedWorkers: 87441,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-1',
    name: '4-1',
    position: { x: 4, y: 1 },
    icon: Object.keys(iconPaths)[80+1 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 5670,
    proportionOfJobs: 754,
    normalizedWorkers: 84806,
    prominence: 2117,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-10',
    name: '4-10',
    position: { x: 4, y: 10 },
    icon: Object.keys(iconPaths)[80+10 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 8873,
    proportionOfJobs: 14508,
    normalizedWorkers: 135192,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-13',
    name: '2-13',
    position: { x: 2, y: 13 },
    icon: Object.keys(iconPaths)[40+13 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 7682,
    proportionOfJobs: 2127,
    normalizedWorkers: 110320,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-18',
    name: '11-18',
    position: { x: 11, y: 18 },
    icon: Object.keys(iconPaths)[220+18 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2492,
    proportionOfJobs: 830,
    normalizedWorkers: 86227,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-14',
    name: '4-14',
    position: { x: 4, y: 14 },
    icon: Object.keys(iconPaths)[80+14 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 8214,
    proportionOfJobs: 3451,
    normalizedWorkers: 120870,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-18',
    name: '6-18',
    position: { x: 6, y: 18 },
    icon: Object.keys(iconPaths)[120+18 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1966,
    proportionOfJobs: 783,
    normalizedWorkers: 91149,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-8',
    name: '5-8',
    position: { x: 5, y: 8 },
    icon: Object.keys(iconPaths)[100+8 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 10383,
    proportionOfJobs: 86385,
    normalizedWorkers: 132408,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-10',
    name: '3-10',
    position: { x: 3, y: 10 },
    icon: Object.keys(iconPaths)[60+10 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 7839,
    proportionOfJobs: 10590,
    normalizedWorkers: 124165,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-6',
    name: '2-6',
    position: { x: 2, y: 6 },
    icon: Object.keys(iconPaths)[40+6 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4988,
    proportionOfJobs: 1434,
    normalizedWorkers: 98741,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '16-13',
    name: '16-13',
    position: { x: 16, y: 13 },
    icon: Object.keys(iconPaths)[320+13 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3429,
    proportionOfJobs: 12891,
    normalizedWorkers: 82946,
    prominence: 124,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-11',
    name: '4-11',
    position: { x: 4, y: 11 },
    icon: Object.keys(iconPaths)[80+11 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 9254,
    proportionOfJobs: 11288,
    normalizedWorkers: 132408,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '9-1',
    name: '9-1',
    position: { x: 9, y: 1 },
    icon: Object.keys(iconPaths)[180+1 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2880,
    proportionOfJobs: 373,
    normalizedWorkers: 85240,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '18-13',
    name: '18-13',
    position: { x: 18, y: 13 },
    icon: Object.keys(iconPaths)[360+13 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2926,
    proportionOfJobs: 1053,
    normalizedWorkers: 71841,
    prominence: 1257,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '18-12',
    name: '18-12',
    position: { x: 18, y: 12 },
    icon: Object.keys(iconPaths)[360+12 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1669,
    proportionOfJobs: 1577,
    normalizedWorkers: 72725,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '18-10',
    name: '18-10',
    position: { x: 18, y: 10 },
    icon: Object.keys(iconPaths)[360+10 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3219,
    proportionOfJobs: 728,
    normalizedWorkers: 75314,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '18-8',
    name: '18-8',
    position: { x: 18, y: 8 },
    icon: Object.keys(iconPaths)[360+8 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2443,
    proportionOfJobs: 867,
    normalizedWorkers: 74881,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '18-6',
    name: '18-6',
    position: { x: 18, y: 6 },
    icon: Object.keys(iconPaths)[360+6 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2345,
    proportionOfJobs: 681,
    normalizedWorkers: 72604,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '18-5',
    name: '18-5',
    position: { x: 18, y: 5 },
    icon: Object.keys(iconPaths)[360+5 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2171,
    proportionOfJobs: 16392,
    normalizedWorkers: 70959,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '18-4',
    name: '18-4',
    position: { x: 18, y: 4 },
    icon: Object.keys(iconPaths)[360+4 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3462,
    proportionOfJobs: 8051,
    normalizedWorkers: 69163,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '15-17',
    name: '15-17',
    position: { x: 15, y: 17 },
    icon: Object.keys(iconPaths)[300+17 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1610,
    proportionOfJobs: 311,
    normalizedWorkers: 74828,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-2',
    name: '3-2',
    position: { x: 3, y: 2 },
    icon: Object.keys(iconPaths)[60+2 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3553,
    proportionOfJobs: 2030,
    normalizedWorkers: 87212,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-13',
    name: '7-13',
    position: { x: 7, y: 13 },
    icon: Object.keys(iconPaths)[140+13 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3366,
    proportionOfJobs: 1200,
    normalizedWorkers: 117948,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-18',
    name: '4-18',
    position: { x: 4, y: 18 },
    icon: Object.keys(iconPaths)[80+18 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2273,
    proportionOfJobs: 1956,
    normalizedWorkers: 88344,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-13',
    name: '11-13',
    position: { x: 11, y: 13 },
    icon: Object.keys(iconPaths)[220+13 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2387,
    proportionOfJobs: 10040,
    normalizedWorkers: 103889,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-14',
    name: '5-14',
    position: { x: 5, y: 14 },
    icon: Object.keys(iconPaths)[100+14 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 5709,
    proportionOfJobs: 4966,
    normalizedWorkers: 121676,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-8',
    name: '6-8',
    position: { x: 6, y: 8 },
    icon: Object.keys(iconPaths)[120+8 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 6921,
    proportionOfJobs: 6298,
    normalizedWorkers: 128321,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-5',
    name: '10-5',
    position: { x: 10, y: 5 },
    icon: Object.keys(iconPaths)[200+5 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2359,
    proportionOfJobs: 1333,
    normalizedWorkers: 98790,
    prominence: 556,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-18',
    name: '10-18',
    position: { x: 10, y: 18 },
    icon: Object.keys(iconPaths)[200+18 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3447,
    proportionOfJobs: 378,
    normalizedWorkers: 87982,
    prominence: 1042,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-15',
    name: '10-15',
    position: { x: 10, y: 15 },
    icon: Object.keys(iconPaths)[200+15 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3092,
    proportionOfJobs: 655,
    normalizedWorkers: 101781,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-1',
    name: '13-1',
    position: { x: 13, y: 1 },
    icon: Object.keys(iconPaths)[260+1 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2608,
    proportionOfJobs: 1065,
    normalizedWorkers: 77721,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-11',
    name: '2-11',
    position: { x: 2, y: 11 },
    icon: Object.keys(iconPaths)[40+11 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 5186,
    proportionOfJobs: 4198,
    normalizedWorkers: 111384,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-2',
    name: '7-2',
    position: { x: 7, y: 2 },
    icon: Object.keys(iconPaths)[140+2 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3070,
    proportionOfJobs: 1137,
    normalizedWorkers: 92058,
    prominence: 741,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-19',
    name: '6-19',
    position: { x: 6, y: 19 },
    icon: Object.keys(iconPaths)[120+19 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2824,
    proportionOfJobs: 503,
    normalizedWorkers: 83907,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-19',
    name: '7-19',
    position: { x: 7, y: 19 },
    icon: Object.keys(iconPaths)[140+19 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2345,
    proportionOfJobs: 365,
    normalizedWorkers: 83482,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-14',
    name: '6-14',
    position: { x: 6, y: 14 },
    icon: Object.keys(iconPaths)[120+14 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 5817,
    proportionOfJobs: 2002,
    normalizedWorkers: 120074,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '9-0',
    name: '9-0',
    position: { x: 9, y: 0 },
    icon: Object.keys(iconPaths)[180+0 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3951,
    proportionOfJobs: 820,
    normalizedWorkers: 79731,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-10',
    name: '11-10',
    position: { x: 11, y: 10 },
    icon: Object.keys(iconPaths)[220+10 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2037,
    proportionOfJobs: 4209,
    normalizedWorkers: 105939,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-3',
    name: '3-3',
    position: { x: 3, y: 3 },
    icon: Object.keys(iconPaths)[60+3 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4766,
    proportionOfJobs: 840,
    normalizedWorkers: 93056,
    prominence: 386,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-14',
    name: '2-14',
    position: { x: 2, y: 14 },
    icon: Object.keys(iconPaths)[40+14 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4443,
    proportionOfJobs: 832,
    normalizedWorkers: 104535,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-6',
    name: '10-6',
    position: { x: 10, y: 6 },
    icon: Object.keys(iconPaths)[200+6 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1390,
    proportionOfJobs: 1263,
    normalizedWorkers: 101144,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-0',
    name: '12-0',
    position: { x: 12, y: 0 },
    icon: Object.keys(iconPaths)[240+0 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4537,
    proportionOfJobs: 1064,
    normalizedWorkers: 76166,
    prominence: 2505,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-16',
    name: '10-16',
    position: { x: 10, y: 16 },
    icon: Object.keys(iconPaths)[200+16 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4204,
    proportionOfJobs: 1253,
    normalizedWorkers: 98421,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-16',
    name: '4-16',
    position: { x: 4, y: 16 },
    icon: Object.keys(iconPaths)[80+16 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4480,
    proportionOfJobs: 6527,
    normalizedWorkers: 104575,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-4',
    name: '7-4',
    position: { x: 7, y: 4 },
    icon: Object.keys(iconPaths)[140+4 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 5088,
    proportionOfJobs: 1347,
    normalizedWorkers: 104739,
    prominence: 1400,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-19',
    name: '12-19',
    position: { x: 12, y: 19 },
    icon: Object.keys(iconPaths)[240+19 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3206,
    proportionOfJobs: 9814,
    normalizedWorkers: 78301,
    prominence: 268,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-19',
    name: '13-19',
    position: { x: 13, y: 19 },
    icon: Object.keys(iconPaths)[260+19 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3111,
    proportionOfJobs: 9111,
    normalizedWorkers: 74895,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '8-19',
    name: '8-19',
    position: { x: 8, y: 19 },
    icon: Object.keys(iconPaths)[160+19 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2713,
    proportionOfJobs: 969,
    normalizedWorkers: 83186,
    prominence: 234,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-13',
    name: '5-13',
    position: { x: 5, y: 13 },
    icon: Object.keys(iconPaths)[100+13 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4608,
    proportionOfJobs: 2347,
    normalizedWorkers: 126066,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '19-4',
    name: '19-4',
    position: { x: 19, y: 4 },
    icon: Object.keys(iconPaths)[380+4 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4521,
    proportionOfJobs: 2559,
    normalizedWorkers: 65393,
    prominence: 2818,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-0',
    name: '10-0',
    position: { x: 10, y: 0 },
    icon: Object.keys(iconPaths)[200+0 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4458,
    proportionOfJobs: 10916,
    normalizedWorkers: 79311,
    prominence: 2306,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-4',
    name: '2-4',
    position: { x: 2, y: 4 },
    icon: Object.keys(iconPaths)[40+4 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4380,
    proportionOfJobs: 1232,
    normalizedWorkers: 91753,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-16',
    name: '5-16',
    position: { x: 5, y: 16 },
    icon: Object.keys(iconPaths)[100+16 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4353,
    proportionOfJobs: 854,
    normalizedWorkers: 107364,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-2',
    name: '2-2',
    position: { x: 2, y: 2 },
    icon: Object.keys(iconPaths)[40+2 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3703,
    proportionOfJobs: 916,
    normalizedWorkers: 81699,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-1',
    name: '5-1',
    position: { x: 5, y: 1 },
    icon: Object.keys(iconPaths)[100+1 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1737,
    proportionOfJobs: 179,
    normalizedWorkers: 84295,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-9',
    name: '13-9',
    position: { x: 13, y: 9 },
    icon: Object.keys(iconPaths)[260+9 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3181,
    proportionOfJobs: 3037,
    normalizedWorkers: 100817,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '9-7',
    name: '9-7',
    position: { x: 9, y: 7 },
    icon: Object.keys(iconPaths)[180+7 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3985,
    proportionOfJobs: 3949,
    normalizedWorkers: 107465,
    prominence: 2014,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-18',
    name: '3-18',
    position: { x: 3, y: 18 },
    icon: Object.keys(iconPaths)[60+18 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1811,
    proportionOfJobs: 3294,
    normalizedWorkers: 83243,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '19-8',
    name: '19-8',
    position: { x: 19, y: 8 },
    icon: Object.keys(iconPaths)[380+8 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3935,
    proportionOfJobs: 1222,
    normalizedWorkers: 70284,
    prominence: 2073,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-19',
    name: '5-19',
    position: { x: 5, y: 19 },
    icon: Object.keys(iconPaths)[100+19 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3846,
    proportionOfJobs: 1115,
    normalizedWorkers: 83486,
    prominence: 1501,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-15',
    name: '5-15',
    position: { x: 5, y: 15 },
    icon: Object.keys(iconPaths)[100+15 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3791,
    proportionOfJobs: 4478,
    normalizedWorkers: 114210,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '14-1',
    name: '14-1',
    position: { x: 14, y: 1 },
    icon: Object.keys(iconPaths)[280+1 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2118,
    proportionOfJobs: 334,
    normalizedWorkers: 73006,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '19-10',
    name: '19-10',
    position: { x: 19, y: 10 },
    icon: Object.keys(iconPaths)[380+10 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3628,
    proportionOfJobs: 482,
    normalizedWorkers: 70169,
    prominence: undefined,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-10',
    name: '6-10',
    position: { x: 6, y: 10 },
    icon: Object.keys(iconPaths)[120+10 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3530,
    proportionOfJobs: 1349,
    normalizedWorkers: 129641,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-12',
    name: '7-12',
    position: { x: 7, y: 12 },
    icon: Object.keys(iconPaths)[140+12 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2075,
    proportionOfJobs: 943,
    normalizedWorkers: 118658,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-11',
    name: '3-11',
    position: { x: 3, y: 11 },
    icon: Object.keys(iconPaths)[60+11 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3432,
    proportionOfJobs: 2998,
    normalizedWorkers: 122387,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-13',
    name: '12-13',
    position: { x: 12, y: 13 },
    icon: Object.keys(iconPaths)[240+13 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2844,
    proportionOfJobs: 2539,
    normalizedWorkers: 101862,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-6',
    name: '3-6',
    position: { x: 3, y: 6 },
    icon: Object.keys(iconPaths)[60+6 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3352,
    proportionOfJobs: 6069,
    normalizedWorkers: 103475,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-0',
    name: '5-0',
    position: { x: 5, y: 0 },
    icon: Object.keys(iconPaths)[100+0 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2667,
    proportionOfJobs: 1387,
    normalizedWorkers: 77763,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-12',
    name: '2-12',
    position: { x: 2, y: 12 },
    icon: Object.keys(iconPaths)[40+12 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2042,
    proportionOfJobs: 4531,
    normalizedWorkers: 110019,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '15-11',
    name: '15-11',
    position: { x: 15, y: 11 },
    icon: Object.keys(iconPaths)[300+11 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3309,
    proportionOfJobs: 614,
    normalizedWorkers: 91119,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-14',
    name: '12-14',
    position: { x: 12, y: 14 },
    icon: Object.keys(iconPaths)[240+14 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3297,
    proportionOfJobs: 1800,
    normalizedWorkers: 100537,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-14',
    name: '13-14',
    position: { x: 13, y: 14 },
    icon: Object.keys(iconPaths)[260+14 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3234,
    proportionOfJobs: 4565,
    normalizedWorkers: 97236,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-9',
    name: '10-9',
    position: { x: 10, y: 9 },
    icon: Object.keys(iconPaths)[200+9 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1765,
    proportionOfJobs: 516,
    normalizedWorkers: 107590,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '14-8',
    name: '14-8',
    position: { x: 14, y: 8 },
    icon: Object.keys(iconPaths)[280+8 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3179,
    proportionOfJobs: 1041,
    normalizedWorkers: 95417,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '15-15',
    name: '15-15',
    position: { x: 15, y: 15 },
    icon: Object.keys(iconPaths)[300+15 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3162,
    proportionOfJobs: 634,
    normalizedWorkers: 83916,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-19',
    name: '10-19',
    position: { x: 10, y: 19 },
    icon: Object.keys(iconPaths)[200+19 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3156,
    proportionOfJobs: 5733,
    normalizedWorkers: 81981,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-6',
    name: '7-6',
    position: { x: 7, y: 6 },
    icon: Object.keys(iconPaths)[140+6 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3150,
    proportionOfJobs: 2261,
    normalizedWorkers: 112188,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '1-12',
    name: '1-12',
    position: { x: 1, y: 12 },
    icon: Object.keys(iconPaths)[20+12 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3093,
    proportionOfJobs: 1634,
    normalizedWorkers: 98438,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-13',
    name: '13-13',
    position: { x: 13, y: 13 },
    icon: Object.keys(iconPaths)[260+13 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3010,
    proportionOfJobs: 472,
    normalizedWorkers: 98947,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-10',
    name: '12-10',
    position: { x: 12, y: 10 },
    icon: Object.keys(iconPaths)[240+10 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2960,
    proportionOfJobs: 23710,
    normalizedWorkers: 103614,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '9-16',
    name: '9-16',
    position: { x: 9, y: 16 },
    icon: Object.keys(iconPaths)[180+16 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2362,
    proportionOfJobs: 453,
    normalizedWorkers: 98607,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-0',
    name: '6-0',
    position: { x: 6, y: 0 },
    icon: Object.keys(iconPaths)[120+0 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1623,
    proportionOfJobs: 833,
    normalizedWorkers: 77747,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-19',
    name: '11-19',
    position: { x: 11, y: 19 },
    icon: Object.keys(iconPaths)[220+19 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2938,
    proportionOfJobs: 1676,
    normalizedWorkers: 80517,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-2',
    name: '13-2',
    position: { x: 13, y: 2 },
    icon: Object.keys(iconPaths)[260+2 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2921,
    proportionOfJobs: 668,
    normalizedWorkers: 81996,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '1-6',
    name: '1-6',
    position: { x: 1, y: 6 },
    icon: Object.keys(iconPaths)[20+6 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2912,
    proportionOfJobs: 710,
    normalizedWorkers: 89379,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '17-8',
    name: '17-8',
    position: { x: 17, y: 8 },
    icon: Object.keys(iconPaths)[340+8 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2131,
    proportionOfJobs: 389,
    normalizedWorkers: 79262,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '15-6',
    name: '15-6',
    position: { x: 15, y: 6 },
    icon: Object.keys(iconPaths)[300+6 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2108,
    proportionOfJobs: 2281,
    normalizedWorkers: 85623,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '14-19',
    name: '14-19',
    position: { x: 14, y: 19 },
    icon: Object.keys(iconPaths)[280+19 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2073,
    proportionOfJobs: 1010,
    normalizedWorkers: 70625,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '16-19',
    name: '16-19',
    position: { x: 16, y: 19 },
    icon: Object.keys(iconPaths)[320+19 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3117,
    proportionOfJobs: 712,
    normalizedWorkers: 64045,
    prominence: undefined,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '18-19',
    name: '18-19',
    position: { x: 18, y: 19 },
    icon: Object.keys(iconPaths)[360+19 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2876,
    proportionOfJobs: 512,
    normalizedWorkers: 57296,
    prominence: undefined,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '17-11',
    name: '17-11',
    position: { x: 17, y: 11 },
    icon: Object.keys(iconPaths)[340+11 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2807,
    proportionOfJobs: 435,
    normalizedWorkers: 79444,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-15',
    name: '3-15',
    position: { x: 3, y: 15 },
    icon: Object.keys(iconPaths)[60+15 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2805,
    proportionOfJobs: 790,
    normalizedWorkers: 105647,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-19',
    name: '3-19',
    position: { x: 3, y: 19 },
    icon: Object.keys(iconPaths)[60+19 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2176,
    proportionOfJobs: 546,
    normalizedWorkers: 76499,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-5',
    name: '6-5',
    position: { x: 6, y: 5 },
    icon: Object.keys(iconPaths)[120+5 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2750,
    proportionOfJobs: 471,
    normalizedWorkers: 108366,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-3',
    name: '13-3',
    position: { x: 13, y: 3 },
    icon: Object.keys(iconPaths)[260+3 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2750,
    proportionOfJobs: 1210,
    normalizedWorkers: 85291,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-7',
    name: '12-7',
    position: { x: 12, y: 7 },
    icon: Object.keys(iconPaths)[240+7 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1878,
    proportionOfJobs: 459,
    normalizedWorkers: 99180,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-15',
    name: '4-15',
    position: { x: 4, y: 15 },
    icon: Object.keys(iconPaths)[80+15 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2677,
    proportionOfJobs: 1475,
    normalizedWorkers: 111516,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-16',
    name: '11-16',
    position: { x: 11, y: 16 },
    icon: Object.keys(iconPaths)[220+16 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2645,
    proportionOfJobs: 1643,
    normalizedWorkers: 96211,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '19-14',
    name: '19-14',
    position: { x: 19, y: 14 },
    icon: Object.keys(iconPaths)[380+14 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2064,
    proportionOfJobs: 654,
    normalizedWorkers: 64484,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '19-6',
    name: '19-6',
    position: { x: 19, y: 6 },
    icon: Object.keys(iconPaths)[380+6 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2603,
    proportionOfJobs: 887,
    normalizedWorkers: 67834,
    prominence: 432,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-1',
    name: '3-1',
    position: { x: 3, y: 1 },
    icon: Object.keys(iconPaths)[60+1 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2599,
    proportionOfJobs: 494,
    normalizedWorkers: 80343,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-7',
    name: '2-7',
    position: { x: 2, y: 7 },
    icon: Object.keys(iconPaths)[40+7 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2589,
    proportionOfJobs: 1647,
    normalizedWorkers: 99585,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-2',
    name: '6-2',
    position: { x: 6, y: 2 },
    icon: Object.keys(iconPaths)[120+2 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2557,
    proportionOfJobs: 3180,
    normalizedWorkers: 91258,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '9-19',
    name: '9-19',
    position: { x: 9, y: 19 },
    icon: Object.keys(iconPaths)[180+19 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2479,
    proportionOfJobs: 1372,
    normalizedWorkers: 82412,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '18-15',
    name: '18-15',
    position: { x: 18, y: 15 },
    icon: Object.keys(iconPaths)[360+15 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1358,
    proportionOfJobs: 517,
    normalizedWorkers: 66747,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-3',
    name: '7-3',
    position: { x: 7, y: 3 },
    icon: Object.keys(iconPaths)[140+3 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2329,
    proportionOfJobs: 802,
    normalizedWorkers: 97834,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-10',
    name: '13-10',
    position: { x: 13, y: 10 },
    icon: Object.keys(iconPaths)[260+10 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2315,
    proportionOfJobs: 1749,
    normalizedWorkers: 100399,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-0',
    name: '4-0',
    position: { x: 4, y: 0 },
    icon: Object.keys(iconPaths)[80+0 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2305,
    proportionOfJobs: 1358,
    normalizedWorkers: 76146,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-15',
    name: '6-15',
    position: { x: 6, y: 15 },
    icon: Object.keys(iconPaths)[120+15 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2294,
    proportionOfJobs: 886,
    normalizedWorkers: 112610,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-10',
    name: '10-10',
    position: { x: 10, y: 10 },
    icon: Object.keys(iconPaths)[200+10 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1734,
    proportionOfJobs: 1158,
    normalizedWorkers: 107359,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-17',
    name: '7-17',
    position: { x: 7, y: 17 },
    icon: Object.keys(iconPaths)[140+17 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2157,
    proportionOfJobs: 767,
    normalizedWorkers: 96926,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-1',
    name: '11-1',
    position: { x: 11, y: 1 },
    icon: Object.keys(iconPaths)[220+1 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2152,
    proportionOfJobs: 145,
    normalizedWorkers: 82596,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-15',
    name: '2-15',
    position: { x: 2, y: 15 },
    icon: Object.keys(iconPaths)[40+15 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2129,
    proportionOfJobs: 744,
    normalizedWorkers: 96559,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-10',
    name: '7-10',
    position: { x: 7, y: 10 },
    icon: Object.keys(iconPaths)[140+10 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2093,
    proportionOfJobs: 1898,
    normalizedWorkers: 120889,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '8-1',
    name: '8-1',
    position: { x: 8, y: 1 },
    icon: Object.keys(iconPaths)[160+1 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2032,
    proportionOfJobs: 82,
    normalizedWorkers: 85273,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-18',
    name: '5-18',
    position: { x: 5, y: 18 },
    icon: Object.keys(iconPaths)[100+18 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2011,
    proportionOfJobs: 261,
    normalizedWorkers: 90865,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-11',
    name: '13-11',
    position: { x: 13, y: 11 },
    icon: Object.keys(iconPaths)[260+11 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1995,
    proportionOfJobs: 1059,
    normalizedWorkers: 99557,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-7',
    name: '11-7',
    position: { x: 11, y: 7 },
    icon: Object.keys(iconPaths)[220+7 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1992,
    proportionOfJobs: 6121,
    normalizedWorkers: 101502,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-16',
    name: '7-16',
    position: { x: 7, y: 16 },
    icon: Object.keys(iconPaths)[140+16 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1979,
    proportionOfJobs: 1137,
    normalizedWorkers: 103267,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-5',
    name: '12-5',
    position: { x: 12, y: 5 },
    icon: Object.keys(iconPaths)[240+5 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1968,
    proportionOfJobs: 370,
    normalizedWorkers: 94079,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-3',
    name: '5-3',
    position: { x: 5, y: 3 },
    icon: Object.keys(iconPaths)[100+3 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1902,
    proportionOfJobs: 5424,
    normalizedWorkers: 95882,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-12',
    name: '11-12',
    position: { x: 11, y: 12 },
    icon: Object.keys(iconPaths)[220+12 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1874,
    proportionOfJobs: 1126,
    normalizedWorkers: 103910,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '15-0',
    name: '15-0',
    position: { x: 15, y: 0 },
    icon: Object.keys(iconPaths)[300+0 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1865,
    proportionOfJobs: 365,
    normalizedWorkers: 64509,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '17-7',
    name: '17-7',
    position: { x: 17, y: 7 },
    icon: Object.keys(iconPaths)[340+7 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1862,
    proportionOfJobs: 649,
    normalizedWorkers: 78067,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-19',
    name: '4-19',
    position: { x: 4, y: 19 },
    icon: Object.keys(iconPaths)[80+19 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1853,
    proportionOfJobs: 667,
    normalizedWorkers: 80250,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-2',
    name: '11-2',
    position: { x: 11, y: 2 },
    icon: Object.keys(iconPaths)[220+2 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1825,
    proportionOfJobs: 405,
    normalizedWorkers: 86325,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-6',
    name: '5-6',
    position: { x: 5, y: 6 },
    icon: Object.keys(iconPaths)[100+6 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1822,
    proportionOfJobs: 44995,
    normalizedWorkers: 110662,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-3',
    name: '2-3',
    position: { x: 2, y: 3 },
    icon: Object.keys(iconPaths)[40+3 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1816,
    proportionOfJobs: 477,
    normalizedWorkers: 86147,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '17-16',
    name: '17-16',
    position: { x: 17, y: 16 },
    icon: Object.keys(iconPaths)[340+16 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1769,
    proportionOfJobs: 421,
    normalizedWorkers: 68913,
    prominence: 411,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-12',
    name: '6-12',
    position: { x: 6, y: 12 },
    icon: Object.keys(iconPaths)[120+12 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1682,
    proportionOfJobs: 1422,
    normalizedWorkers: 124301,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-16',
    name: '3-16',
    position: { x: 3, y: 16 },
    icon: Object.keys(iconPaths)[60+16 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1627,
    proportionOfJobs: 310,
    normalizedWorkers: 97207,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-0',
    name: '11-0',
    position: { x: 11, y: 0 },
    icon: Object.keys(iconPaths)[220+0 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1595,
    proportionOfJobs: 15141,
    normalizedWorkers: 76968,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-17',
    name: '3-17',
    position: { x: 3, y: 17 },
    icon: Object.keys(iconPaths)[60+17 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1560,
    proportionOfJobs: 232,
    normalizedWorkers: 90015,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '15-10',
    name: '15-10',
    position: { x: 15, y: 10 },
    icon: Object.keys(iconPaths)[300+10 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1534,
    proportionOfJobs: 484,
    normalizedWorkers: 90851,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-19',
    name: '2-19',
    position: { x: 2, y: 19 },
    icon: Object.keys(iconPaths)[40+19 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1494,
    proportionOfJobs: 415,
    normalizedWorkers: 71440,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-11',
    name: '11-11',
    position: { x: 11, y: 11 },
    icon: Object.keys(iconPaths)[220+11 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1487,
    proportionOfJobs: 8644,
    normalizedWorkers: 104339,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '8-13',
    name: '8-13',
    position: { x: 8, y: 13 },
    icon: Object.keys(iconPaths)[160+13 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1452,
    proportionOfJobs: 1472,
    normalizedWorkers: 111325,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-4',
    name: '13-4',
    position: { x: 13, y: 4 },
    icon: Object.keys(iconPaths)[260+4 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1383,
    proportionOfJobs: 176,
    normalizedWorkers: 88055,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-12',
    name: '12-12',
    position: { x: 12, y: 12 },
    icon: Object.keys(iconPaths)[240+12 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1345,
    proportionOfJobs: 1430,
    normalizedWorkers: 101432,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-0',
    name: '7-0',
    position: { x: 7, y: 0 },
    icon: Object.keys(iconPaths)[140+0 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1317,
    proportionOfJobs: 10368,
    normalizedWorkers: 77865,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '9-10',
    name: '9-10',
    position: { x: 9, y: 10 },
    icon: Object.keys(iconPaths)[180+10 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1037,
    proportionOfJobs: 611,
    normalizedWorkers: 109225,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-1',
    name: '7-1',
    position: { x: 7, y: 1 },
    icon: Object.keys(iconPaths)[140+1 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 959,
    proportionOfJobs: 4459,
    normalizedWorkers: 84681,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-11',
    name: '6-11',
    position: { x: 6, y: 11 },
    icon: Object.keys(iconPaths)[120+11 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 526,
    proportionOfJobs: 25731,
    normalizedWorkers: 125143,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '18-1',
    name: '18-1',
    position: { x: 18, y: 1 },
    icon: Object.keys(iconPaths)[360+1 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3007,
    proportionOfJobs: 661,
    normalizedWorkers: 59154,
    prominence: undefined,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '16-3',
    name: '16-3',
    position: { x: 16, y: 3 },
    icon: Object.keys(iconPaths)[320+3 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3238,
    proportionOfJobs: 869,
    normalizedWorkers: 72753,
    prominence: undefined,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-10',
    name: '5-10',
    position: { x: 5, y: 10 },
    icon: Object.keys(iconPaths)[100+10 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 5159,
    proportionOfJobs: 9969,
    normalizedWorkers: 135992,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '8-5',
    name: '8-5',
    position: { x: 8, y: 5 },
    icon: Object.keys(iconPaths)[160+5 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 4704,
    proportionOfJobs: 1493,
    normalizedWorkers: 106257,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '1-10',
    name: '1-10',
    position: { x: 1, y: 10 },
    icon: Object.keys(iconPaths)[20+10 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2845,
    proportionOfJobs: 962,
    normalizedWorkers: 97030,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-13',
    name: '4-13',
    position: { x: 4, y: 13 },
    icon: Object.keys(iconPaths)[80+13 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3760,
    proportionOfJobs: 1848,
    normalizedWorkers: 123800,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '8-12',
    name: '8-12',
    position: { x: 8, y: 12 },
    icon: Object.keys(iconPaths)[160+12 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3496,
    proportionOfJobs: 10701,
    normalizedWorkers: 113626,
    prominence: 130,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-7',
    name: '7-7',
    position: { x: 7, y: 7 },
    icon: Object.keys(iconPaths)[140+7 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3344,
    proportionOfJobs: 2812,
    normalizedWorkers: 115835,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-8',
    name: '4-8',
    position: { x: 4, y: 8 },
    icon: Object.keys(iconPaths)[80+8 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 3230,
    proportionOfJobs: 74673,
    normalizedWorkers: 123819,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-13',
    name: '10-13',
    position: { x: 10, y: 13 },
    icon: Object.keys(iconPaths)[200+13 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2714,
    proportionOfJobs: 3056,
    normalizedWorkers: 105282,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '8-18',
    name: '8-18',
    position: { x: 8, y: 18 },
    icon: Object.keys(iconPaths)[160+18 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2674,
    proportionOfJobs: 504,
    normalizedWorkers: 89472,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '1-13',
    name: '1-13',
    position: { x: 1, y: 13 },
    icon: Object.keys(iconPaths)[20+13 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 2591,
    proportionOfJobs: 1667,
    normalizedWorkers: 96578,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '9-2',
    name: '9-2',
    position: { x: 9, y: 2 },
    icon: Object.keys(iconPaths)[180+2 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1999,
    proportionOfJobs: 236,
    normalizedWorkers: 89633,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '15-8',
    name: '15-8',
    position: { x: 15, y: 8 },
    icon: Object.keys(iconPaths)[300+8 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1994,
    proportionOfJobs: 404,
    normalizedWorkers: 89587,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-8',
    name: '10-8',
    position: { x: 10, y: 8 },
    icon: Object.keys(iconPaths)[200+8 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1971,
    proportionOfJobs: 266,
    normalizedWorkers: 106026,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-4',
    name: '11-4',
    position: { x: 11, y: 4 },
    icon: Object.keys(iconPaths)[220+4 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1803,
    proportionOfJobs: 517,
    normalizedWorkers: 93298,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '16-6',
    name: '16-6',
    position: { x: 16, y: 6 },
    icon: Object.keys(iconPaths)[320+6 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1703,
    proportionOfJobs: 1392,
    normalizedWorkers: 80703,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-9',
    name: '3-9',
    position: { x: 3, y: 9 },
    icon: Object.keys(iconPaths)[60+9 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1620,
    proportionOfJobs: 6354,
    normalizedWorkers: 118783,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '9-3',
    name: '9-3',
    position: { x: 9, y: 3 },
    icon: Object.keys(iconPaths)[180+3 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1589,
    proportionOfJobs: 641,
    normalizedWorkers: 93766,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '8-16',
    name: '8-16',
    position: { x: 8, y: 16 },
    icon: Object.keys(iconPaths)[160+16 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1434,
    proportionOfJobs: 550,
    normalizedWorkers: 100013,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-1',
    name: '2-1',
    position: { x: 2, y: 1 },
    icon: Object.keys(iconPaths)[40+1 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1400,
    proportionOfJobs: 89,
    normalizedWorkers: 74749,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-6',
    name: '11-6',
    position: { x: 11, y: 6 },
    icon: Object.keys(iconPaths)[220+6 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 1314,
    proportionOfJobs: 393,
    normalizedWorkers: 98623,
    prominence: 0,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '0-0',
    name: '0-0',
    position: { x: 0, y: 0 },
    icon: Object.keys(iconPaths)[0+0 % Object.keys(iconPaths).length],
    color: 'black',
    residents: 0,
    proportionOfJobs: 0,
    normalizedWorkers: 59371,
    prominence: undefined,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  }
];

export default neighborhoods;
