import { iconPaths } from "./iconPaths";
import { createArcStarPath, createCirclePath, createPolarRosePath, createPolygonPath, createStarPath } from "./utils/svgShapes";

// Generated neighborhoods from GeoJSON
const neighborhoods = [
  {
    id: '5-9',
    name: '5-9',
    position: { x: 5, y: 9 },
    icon: createCirclePath(7.5, {x: 7.5, y: 7.5}),
    color: 'black',
    residents: 25231,
    proportionOfJobs: 57811,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-9',
    name: '4-9',
    position: { x: 4, y: 9 },
    icon: createPolygonPath(3, 7.5, {x: 7.5, y: 7.5}),
    color: 'black',
    residents: 18180,
    proportionOfJobs: 104108,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-8',
    name: '5-8',
    position: { x: 5, y: 8 },
    icon: createPolygonPath(4, 7.5, {x: 7.5, y: 7.5}),
    color: 'black',
    residents: 10383,
    proportionOfJobs: 86385,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-12',
    name: '5-12',
    position: { x: 5, y: 12 },
    icon: createPolygonPath(5, 7.5, {x: 7.5, y: 7.5}),
    color: 'black',
    residents: 10348,
    proportionOfJobs: 7388,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-9',
    name: '6-9',
    position: { x: 6, y: 9 },
    icon: createPolygonPath(6, 7.5, {x: 7.5, y: 7.5}),
    color: 'black',
    residents: 9505,
    proportionOfJobs: 5722,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-11',
    name: '4-11',
    position: { x: 4, y: 11 },
    icon: createStarPath(3, 7.5, 2, {x: 7.5, y: 7.5}),
    color: 'black',
    residents: 9254,
    proportionOfJobs: 11288,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-10',
    name: '4-10',
    position: { x: 4, y: 10 },
    icon: createStarPath(4, 7.5, 3, {x: 7.5, y: 7.5}),
    color: 'black',
    residents: 8873,
    proportionOfJobs: 14508,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-14',
    name: '3-14',
    position: { x: 3, y: 14 },
    icon: createStarPath(5, 7.5, 3, {x: 7.5, y: 7.5}),
    color: 'black',
    residents: 8824,
    proportionOfJobs: 2729,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-9',
    name: '11-9',
    position: { x: 11, y: 9 },
    icon: createStarPath(8, 7.5, 4, {x: 7.5, y: 7.5}),
    color: 'black',
    residents: 8365,
    proportionOfJobs: 59803,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-14',
    name: '4-14',
    position: { x: 4, y: 14 },
    icon: createPolarRosePath(3, 7.5, 0.25, {x: 7.5, y: 7.5}, 30)
      + createCirclePath(2, {x: 7.5, y: 7.5}, true),
    color: 'black',
    residents: 8214,
    proportionOfJobs: 3451,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-10',
    name: '3-10',
    position: { x: 3, y: 10 },
    icon: createPolarRosePath(4, 7.5, 0.25, {x: 7.5, y: 7.5}, 22.5)
      + createCirclePath(3, {x: 7.5, y: 7.5}, true),
    color: 'black',
    residents: 7839,
    proportionOfJobs: 10590,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-13',
    name: '2-13',
    position: { x: 2, y: 13 },
    icon: createPolarRosePath(5, 7.5, 0.25, {x: 7.5, y: 7.5}, 18)
      + createCirclePath(4, {x: 7.5, y: 7.5}, true),
    color: 'black',
    residents: 7682,
    proportionOfJobs: 2127,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-5',
    name: '2-5',
    position: { x: 2, y: 5 },
    icon: createPolygonPath(4, 7.5, {x: 7.5, y: 7.5}, 45),
    color: 'black',
    residents: 7437,
    proportionOfJobs: 6351,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-13',
    name: '6-13',
    position: { x: 6, y: 13 },
    icon: createPolarRosePath(2, 7.5, 0.25, {x: 7.5, y: 7.5}, 45)
      + createCirclePath(2, {x: 7.5, y: 7.5}, true),
    color: 'black',
    residents: 7220,
    proportionOfJobs: 6703,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-8',
    name: '6-8',
    position: { x: 6, y: 8 },
    icon: createArcStarPath(3, 7.5, 3, {x: 7.5, y: 7.5}, -60),
    color: 'black',
    residents: 6921,
    proportionOfJobs: 6298,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '14-14',
    name: '14-14',
    position: { x: 14, y: 14 },
    icon: createArcStarPath(4, 7.5, 2, {x: 7.5, y: 7.5}),
    color: 'black',
    residents: 6074,
    proportionOfJobs: 7171,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-14',
    name: '6-14',
    position: { x: 6, y: 14 },
    icon: createArcStarPath(4, 7.5, 3, {x: 7.5, y: 7.5}),
    color: 'black',
    residents: 5817,
    proportionOfJobs: 2002,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-14',
    name: '5-14',
    position: { x: 5, y: 14 },
    icon: createArcStarPath(4, 7.5, 4, {x: 7.5, y: 7.5}, 135),
    color: 'black',
    residents: 5709,
    proportionOfJobs: 4966,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-1',
    name: '4-1',
    position: { x: 4, y: 1 },
    icon: createArcStarPath(5, 7.5, 2, {x: 7.5, y: 7.5}, 90),
    color: 'black',
    residents: 5670,
    proportionOfJobs: 754,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '14-9',
    name: '14-9',
    position: { x: 14, y: 9 },
    icon: createArcStarPath(5, 7.5, 3, {x: 7.5, y: 7.5}, 36),
    color: 'black',
    residents: 5523,
    proportionOfJobs: 3719,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-11',
    name: '2-11',
    position: { x: 2, y: 11 },
    icon: createArcStarPath(5, 7.5, 4, {x: 7.5, y: 7.5}, 0),
    color: 'black',
    residents: 5186,
    proportionOfJobs: 4198,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-10',
    name: '5-10',
    position: { x: 5, y: 10 },
    icon: createArcStarPath(5, 7.5, 5, {x: 7.5, y: 7.5}, -36),
    color: 'black',
    residents: 5159,
    proportionOfJobs: 9969,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-4',
    name: '7-4',
    position: { x: 7, y: 4 },
    icon: createPolygonPath(4, i => (i < 2) ? 4 : 7.5, {x: 7.5, y: 7.5}, -45),
    color: 'black',
    residents: 5088,
    proportionOfJobs: 1347,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-12',
    name: '3-12',
    position: { x: 3, y: 12 },
    icon: createPolygonPath(5, i => (i === 1 || i === 4) ? 5 : 7.5, {x: 7.5, y: 7.5}),
    color: 'black',
    residents: 5003,
    proportionOfJobs: 6613,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-6',
    name: '2-6',
    position: { x: 2, y: 6 },
    icon: Object.keys(iconPaths)[40+6],
    color: 'black',
    residents: 4988,
    proportionOfJobs: 1434,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-15',
    name: '11-15',
    position: { x: 11, y: 15 },
    icon: Object.keys(iconPaths)[220+15],
    color: 'black',
    residents: 4913,
    proportionOfJobs: 4759,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-4',
    name: '6-4',
    position: { x: 6, y: 4 },
    icon: Object.keys(iconPaths)[120+4],
    color: 'black',
    residents: 4886,
    proportionOfJobs: 829,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-6',
    name: '6-6',
    position: { x: 6, y: 6 },
    icon: Object.keys(iconPaths)[120+6],
    color: 'black',
    residents: 4872,
    proportionOfJobs: 6098,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-3',
    name: '3-3',
    position: { x: 3, y: 3 },
    icon: Object.keys(iconPaths)[60+3],
    color: 'black',
    residents: 4766,
    proportionOfJobs: 840,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-17',
    name: '4-17',
    position: { x: 4, y: 17 },
    icon: Object.keys(iconPaths)[80+17],
    color: 'black',
    residents: 4710,
    proportionOfJobs: 2464,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '8-5',
    name: '8-5',
    position: { x: 8, y: 5 },
    icon: Object.keys(iconPaths)[160+5],
    color: 'black',
    residents: 4704,
    proportionOfJobs: 1493,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-12',
    name: '4-12',
    position: { x: 4, y: 12 },
    icon: Object.keys(iconPaths)[80+12],
    color: 'black',
    residents: 4696,
    proportionOfJobs: 2351,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-16',
    name: '6-16',
    position: { x: 6, y: 16 },
    icon: Object.keys(iconPaths)[120+16],
    color: 'black',
    residents: 4666,
    proportionOfJobs: 1742,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-13',
    name: '5-13',
    position: { x: 5, y: 13 },
    icon: Object.keys(iconPaths)[100+13],
    color: 'black',
    residents: 4608,
    proportionOfJobs: 2347,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-0',
    name: '12-0',
    position: { x: 12, y: 0 },
    icon: Object.keys(iconPaths)[240+0],
    color: 'black',
    residents: 4537,
    proportionOfJobs: 1064,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '19-4',
    name: '19-4',
    position: { x: 19, y: 4 },
    icon: Object.keys(iconPaths)[380+4],
    color: 'black',
    residents: 4521,
    proportionOfJobs: 2559,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-16',
    name: '4-16',
    position: { x: 4, y: 16 },
    icon: Object.keys(iconPaths)[80+16],
    color: 'black',
    residents: 4480,
    proportionOfJobs: 6527,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-0',
    name: '10-0',
    position: { x: 10, y: 0 },
    icon: Object.keys(iconPaths)[200+0],
    color: 'black',
    residents: 4458,
    proportionOfJobs: 10916,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-14',
    name: '2-14',
    position: { x: 2, y: 14 },
    icon: Object.keys(iconPaths)[40+14],
    color: 'black',
    residents: 4443,
    proportionOfJobs: 832,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-4',
    name: '2-4',
    position: { x: 2, y: 4 },
    icon: Object.keys(iconPaths)[40+4],
    color: 'black',
    residents: 4380,
    proportionOfJobs: 1232,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-16',
    name: '5-16',
    position: { x: 5, y: 16 },
    icon: Object.keys(iconPaths)[100+16],
    color: 'black',
    residents: 4353,
    proportionOfJobs: 854,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '14-11',
    name: '14-11',
    position: { x: 14, y: 11 },
    icon: Object.keys(iconPaths)[280+11],
    color: 'black',
    residents: 4351,
    proportionOfJobs: 81513,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-14',
    name: '11-14',
    position: { x: 11, y: 14 },
    icon: Object.keys(iconPaths)[220+14],
    color: 'black',
    residents: 4320,
    proportionOfJobs: 2795,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-1',
    name: '12-1',
    position: { x: 12, y: 1 },
    icon: Object.keys(iconPaths)[240+1],
    color: 'black',
    residents: 4304,
    proportionOfJobs: 1373,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-5',
    name: '7-5',
    position: { x: 7, y: 5 },
    icon: Object.keys(iconPaths)[140+5],
    color: 'black',
    residents: 4294,
    proportionOfJobs: 3277,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-13',
    name: '3-13',
    position: { x: 3, y: 13 },
    icon: Object.keys(iconPaths)[60+13],
    color: 'black',
    residents: 4259,
    proportionOfJobs: 741,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-14',
    name: '7-14',
    position: { x: 7, y: 14 },
    icon: Object.keys(iconPaths)[140+14],
    color: 'black',
    residents: 4226,
    proportionOfJobs: 997,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-16',
    name: '10-16',
    position: { x: 10, y: 16 },
    icon: Object.keys(iconPaths)[200+16],
    color: 'black',
    residents: 4204,
    proportionOfJobs: 1253,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-4',
    name: '3-4',
    position: { x: 3, y: 4 },
    icon: Object.keys(iconPaths)[60+4],
    color: 'black',
    residents: 4200,
    proportionOfJobs: 1063,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '9-7',
    name: '9-7',
    position: { x: 9, y: 7 },
    icon: Object.keys(iconPaths)[180+7],
    color: 'black',
    residents: 3985,
    proportionOfJobs: 3949,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '9-0',
    name: '9-0',
    position: { x: 9, y: 0 },
    icon: Object.keys(iconPaths)[180+0],
    color: 'black',
    residents: 3951,
    proportionOfJobs: 820,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '19-8',
    name: '19-8',
    position: { x: 19, y: 8 },
    icon: Object.keys(iconPaths)[380+8],
    color: 'black',
    residents: 3935,
    proportionOfJobs: 1222,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-19',
    name: '5-19',
    position: { x: 5, y: 19 },
    icon: Object.keys(iconPaths)[100+19],
    color: 'black',
    residents: 3846,
    proportionOfJobs: 1115,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '14-5',
    name: '14-5',
    position: { x: 14, y: 5 },
    icon: Object.keys(iconPaths)[280+5],
    color: 'black',
    residents: 3845,
    proportionOfJobs: 644,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-15',
    name: '5-15',
    position: { x: 5, y: 15 },
    icon: Object.keys(iconPaths)[100+15],
    color: 'black',
    residents: 3791,
    proportionOfJobs: 4478,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-13',
    name: '4-13',
    position: { x: 4, y: 13 },
    icon: Object.keys(iconPaths)[80+13],
    color: 'black',
    residents: 3760,
    proportionOfJobs: 1848,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '14-16',
    name: '14-16',
    position: { x: 14, y: 16 },
    icon: Object.keys(iconPaths)[280+16],
    color: 'black',
    residents: 3707,
    proportionOfJobs: 1280,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-2',
    name: '2-2',
    position: { x: 2, y: 2 },
    icon: Object.keys(iconPaths)[40+2],
    color: 'black',
    residents: 3703,
    proportionOfJobs: 916,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-7',
    name: '6-7',
    position: { x: 6, y: 7 },
    icon: Object.keys(iconPaths)[120+7],
    color: 'black',
    residents: 3688,
    proportionOfJobs: 3754,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '15-9',
    name: '15-9',
    position: { x: 15, y: 9 },
    icon: Object.keys(iconPaths)[300+9],
    color: 'black',
    residents: 3684,
    proportionOfJobs: 1925,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '14-13',
    name: '14-13',
    position: { x: 14, y: 13 },
    icon: Object.keys(iconPaths)[280+13],
    color: 'black',
    residents: 3668,
    proportionOfJobs: 11465,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '19-10',
    name: '19-10',
    position: { x: 19, y: 10 },
    icon: Object.keys(iconPaths)[380+10],
    color: 'black',
    residents: 3628,
    proportionOfJobs: 482,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-16',
    name: '12-16',
    position: { x: 12, y: 16 },
    icon: Object.keys(iconPaths)[240+16],
    color: 'black',
    residents: 3577,
    proportionOfJobs: 9864,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-2',
    name: '3-2',
    position: { x: 3, y: 2 },
    icon: Object.keys(iconPaths)[60+2],
    color: 'black',
    residents: 3553,
    proportionOfJobs: 2030,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-17',
    name: '5-17',
    position: { x: 5, y: 17 },
    icon: Object.keys(iconPaths)[100+17],
    color: 'black',
    residents: 3551,
    proportionOfJobs: 2220,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-10',
    name: '6-10',
    position: { x: 6, y: 10 },
    icon: Object.keys(iconPaths)[120+10],
    color: 'black',
    residents: 3530,
    proportionOfJobs: 1349,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '8-12',
    name: '8-12',
    position: { x: 8, y: 12 },
    icon: Object.keys(iconPaths)[160+12],
    color: 'black',
    residents: 3496,
    proportionOfJobs: 10701,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '18-4',
    name: '18-4',
    position: { x: 18, y: 4 },
    icon: Object.keys(iconPaths)[360+4],
    color: 'black',
    residents: 3462,
    proportionOfJobs: 8051,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-18',
    name: '10-18',
    position: { x: 10, y: 18 },
    icon: Object.keys(iconPaths)[200+18],
    color: 'black',
    residents: 3447,
    proportionOfJobs: 378,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-11',
    name: '3-11',
    position: { x: 3, y: 11 },
    icon: Object.keys(iconPaths)[60+11],
    color: 'black',
    residents: 3432,
    proportionOfJobs: 2998,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '16-13',
    name: '16-13',
    position: { x: 16, y: 13 },
    icon: Object.keys(iconPaths)[320+13],
    color: 'black',
    residents: 3429,
    proportionOfJobs: 12891,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '15-5',
    name: '15-5',
    position: { x: 15, y: 5 },
    icon: Object.keys(iconPaths)[300+5],
    color: 'black',
    residents: 3426,
    proportionOfJobs: 545,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-13',
    name: '7-13',
    position: { x: 7, y: 13 },
    icon: Object.keys(iconPaths)[140+13],
    color: 'black',
    residents: 3366,
    proportionOfJobs: 1200,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-6',
    name: '3-6',
    position: { x: 3, y: 6 },
    icon: Object.keys(iconPaths)[60+6],
    color: 'black',
    residents: 3352,
    proportionOfJobs: 6069,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-7',
    name: '7-7',
    position: { x: 7, y: 7 },
    icon: Object.keys(iconPaths)[140+7],
    color: 'black',
    residents: 3344,
    proportionOfJobs: 2812,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-3',
    name: '4-3',
    position: { x: 4, y: 3 },
    icon: Object.keys(iconPaths)[80+3],
    color: 'black',
    residents: 3332,
    proportionOfJobs: 2427,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '15-11',
    name: '15-11',
    position: { x: 15, y: 11 },
    icon: Object.keys(iconPaths)[300+11],
    color: 'black',
    residents: 3309,
    proportionOfJobs: 614,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '15-14',
    name: '15-14',
    position: { x: 15, y: 14 },
    icon: Object.keys(iconPaths)[300+14],
    color: 'black',
    residents: 3305,
    proportionOfJobs: 705,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-14',
    name: '12-14',
    position: { x: 12, y: 14 },
    icon: Object.keys(iconPaths)[240+14],
    color: 'black',
    residents: 3297,
    proportionOfJobs: 1800,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '16-3',
    name: '16-3',
    position: { x: 16, y: 3 },
    icon: Object.keys(iconPaths)[320+3],
    color: 'black',
    residents: 3238,
    proportionOfJobs: 869,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-11',
    name: '5-11',
    position: { x: 5, y: 11 },
    icon: Object.keys(iconPaths)[100+11],
    color: 'black',
    residents: 3236,
    proportionOfJobs: 2885,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-14',
    name: '13-14',
    position: { x: 13, y: 14 },
    icon: Object.keys(iconPaths)[260+14],
    color: 'black',
    residents: 3234,
    proportionOfJobs: 4565,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-8',
    name: '4-8',
    position: { x: 4, y: 8 },
    icon: Object.keys(iconPaths)[80+8],
    color: 'black',
    residents: 3230,
    proportionOfJobs: 74673,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '18-10',
    name: '18-10',
    position: { x: 18, y: 10 },
    icon: Object.keys(iconPaths)[360+10],
    color: 'black',
    residents: 3219,
    proportionOfJobs: 728,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-19',
    name: '12-19',
    position: { x: 12, y: 19 },
    icon: Object.keys(iconPaths)[240+19],
    color: 'black',
    residents: 3206,
    proportionOfJobs: 9814,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-9',
    name: '13-9',
    position: { x: 13, y: 9 },
    icon: Object.keys(iconPaths)[260+9],
    color: 'black',
    residents: 3181,
    proportionOfJobs: 3037,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '14-8',
    name: '14-8',
    position: { x: 14, y: 8 },
    icon: Object.keys(iconPaths)[280+8],
    color: 'black',
    residents: 3179,
    proportionOfJobs: 1041,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '15-15',
    name: '15-15',
    position: { x: 15, y: 15 },
    icon: Object.keys(iconPaths)[300+15],
    color: 'black',
    residents: 3162,
    proportionOfJobs: 634,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-19',
    name: '10-19',
    position: { x: 10, y: 19 },
    icon: Object.keys(iconPaths)[200+19],
    color: 'black',
    residents: 3156,
    proportionOfJobs: 5733,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-6',
    name: '7-6',
    position: { x: 7, y: 6 },
    icon: Object.keys(iconPaths)[140+6],
    color: 'black',
    residents: 3150,
    proportionOfJobs: 2261,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '16-19',
    name: '16-19',
    position: { x: 16, y: 19 },
    icon: Object.keys(iconPaths)[320+19],
    color: 'black',
    residents: 3117,
    proportionOfJobs: 712,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-19',
    name: '13-19',
    position: { x: 13, y: 19 },
    icon: Object.keys(iconPaths)[260+19],
    color: 'black',
    residents: 3111,
    proportionOfJobs: 9111,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '1-12',
    name: '1-12',
    position: { x: 1, y: 12 },
    icon: Object.keys(iconPaths)[20+12],
    color: 'black',
    residents: 3093,
    proportionOfJobs: 1634,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-15',
    name: '10-15',
    position: { x: 10, y: 15 },
    icon: Object.keys(iconPaths)[200+15],
    color: 'black',
    residents: 3092,
    proportionOfJobs: 655,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-2',
    name: '7-2',
    position: { x: 7, y: 2 },
    icon: Object.keys(iconPaths)[140+2],
    color: 'black',
    residents: 3070,
    proportionOfJobs: 1137,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-6',
    name: '13-6',
    position: { x: 13, y: 6 },
    icon: Object.keys(iconPaths)[260+6],
    color: 'black',
    residents: 3067,
    proportionOfJobs: 15264,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-13',
    name: '13-13',
    position: { x: 13, y: 13 },
    icon: Object.keys(iconPaths)[260+13],
    color: 'black',
    residents: 3010,
    proportionOfJobs: 472,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '18-1',
    name: '18-1',
    position: { x: 18, y: 1 },
    icon: Object.keys(iconPaths)[360+1],
    color: 'black',
    residents: 3007,
    proportionOfJobs: 661,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-18',
    name: '12-18',
    position: { x: 12, y: 18 },
    icon: Object.keys(iconPaths)[240+18],
    color: 'black',
    residents: 2976,
    proportionOfJobs: 1578,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-10',
    name: '12-10',
    position: { x: 12, y: 10 },
    icon: Object.keys(iconPaths)[240+10],
    color: 'black',
    residents: 2960,
    proportionOfJobs: 23710,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-19',
    name: '11-19',
    position: { x: 11, y: 19 },
    icon: Object.keys(iconPaths)[220+19],
    color: 'black',
    residents: 2938,
    proportionOfJobs: 1676,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '18-13',
    name: '18-13',
    position: { x: 18, y: 13 },
    icon: Object.keys(iconPaths)[360+13],
    color: 'black',
    residents: 2926,
    proportionOfJobs: 1053,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-2',
    name: '13-2',
    position: { x: 13, y: 2 },
    icon: Object.keys(iconPaths)[260+2],
    color: 'black',
    residents: 2921,
    proportionOfJobs: 668,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '1-6',
    name: '1-6',
    position: { x: 1, y: 6 },
    icon: Object.keys(iconPaths)[20+6],
    color: 'black',
    residents: 2912,
    proportionOfJobs: 710,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-8',
    name: '13-8',
    position: { x: 13, y: 8 },
    icon: Object.keys(iconPaths)[260+8],
    color: 'black',
    residents: 2912,
    proportionOfJobs: 748,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '9-1',
    name: '9-1',
    position: { x: 9, y: 1 },
    icon: Object.keys(iconPaths)[180+1],
    color: 'black',
    residents: 2880,
    proportionOfJobs: 373,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '18-19',
    name: '18-19',
    position: { x: 18, y: 19 },
    icon: Object.keys(iconPaths)[360+19],
    color: 'black',
    residents: 2876,
    proportionOfJobs: 512,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-16',
    name: '13-16',
    position: { x: 13, y: 16 },
    icon: Object.keys(iconPaths)[260+16],
    color: 'black',
    residents: 2858,
    proportionOfJobs: 2653,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-4',
    name: '12-4',
    position: { x: 12, y: 4 },
    icon: Object.keys(iconPaths)[240+4],
    color: 'black',
    residents: 2855,
    proportionOfJobs: 1310,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '1-10',
    name: '1-10',
    position: { x: 1, y: 10 },
    icon: Object.keys(iconPaths)[20+10],
    color: 'black',
    residents: 2845,
    proportionOfJobs: 962,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-13',
    name: '12-13',
    position: { x: 12, y: 13 },
    icon: Object.keys(iconPaths)[240+13],
    color: 'black',
    residents: 2844,
    proportionOfJobs: 2539,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-19',
    name: '6-19',
    position: { x: 6, y: 19 },
    icon: Object.keys(iconPaths)[120+19],
    color: 'black',
    residents: 2824,
    proportionOfJobs: 503,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '14-12',
    name: '14-12',
    position: { x: 14, y: 12 },
    icon: Object.keys(iconPaths)[280+12],
    color: 'black',
    residents: 2824,
    proportionOfJobs: 358,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '17-11',
    name: '17-11',
    position: { x: 17, y: 11 },
    icon: Object.keys(iconPaths)[340+11],
    color: 'black',
    residents: 2807,
    proportionOfJobs: 435,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-15',
    name: '3-15',
    position: { x: 3, y: 15 },
    icon: Object.keys(iconPaths)[60+15],
    color: 'black',
    residents: 2805,
    proportionOfJobs: 790,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-5',
    name: '6-5',
    position: { x: 6, y: 5 },
    icon: Object.keys(iconPaths)[120+5],
    color: 'black',
    residents: 2750,
    proportionOfJobs: 471,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-3',
    name: '13-3',
    position: { x: 13, y: 3 },
    icon: Object.keys(iconPaths)[260+3],
    color: 'black',
    residents: 2750,
    proportionOfJobs: 1210,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-13',
    name: '10-13',
    position: { x: 10, y: 13 },
    icon: Object.keys(iconPaths)[200+13],
    color: 'black',
    residents: 2714,
    proportionOfJobs: 3056,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '8-19',
    name: '8-19',
    position: { x: 8, y: 19 },
    icon: Object.keys(iconPaths)[160+19],
    color: 'black',
    residents: 2713,
    proportionOfJobs: 969,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-15',
    name: '4-15',
    position: { x: 4, y: 15 },
    icon: Object.keys(iconPaths)[80+15],
    color: 'black',
    residents: 2677,
    proportionOfJobs: 1475,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '8-18',
    name: '8-18',
    position: { x: 8, y: 18 },
    icon: Object.keys(iconPaths)[160+18],
    color: 'black',
    residents: 2674,
    proportionOfJobs: 504,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-4',
    name: '4-4',
    position: { x: 4, y: 4 },
    icon: Object.keys(iconPaths)[80+4],
    color: 'black',
    residents: 2671,
    proportionOfJobs: 1120,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-0',
    name: '5-0',
    position: { x: 5, y: 0 },
    icon: Object.keys(iconPaths)[100+0],
    color: 'black',
    residents: 2667,
    proportionOfJobs: 1387,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-16',
    name: '11-16',
    position: { x: 11, y: 16 },
    icon: Object.keys(iconPaths)[220+16],
    color: 'black',
    residents: 2645,
    proportionOfJobs: 1643,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-1',
    name: '13-1',
    position: { x: 13, y: 1 },
    icon: Object.keys(iconPaths)[260+1],
    color: 'black',
    residents: 2608,
    proportionOfJobs: 1065,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '19-6',
    name: '19-6',
    position: { x: 19, y: 6 },
    icon: Object.keys(iconPaths)[380+6],
    color: 'black',
    residents: 2603,
    proportionOfJobs: 887,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-1',
    name: '3-1',
    position: { x: 3, y: 1 },
    icon: Object.keys(iconPaths)[60+1],
    color: 'black',
    residents: 2599,
    proportionOfJobs: 494,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '1-13',
    name: '1-13',
    position: { x: 1, y: 13 },
    icon: Object.keys(iconPaths)[20+13],
    color: 'black',
    residents: 2591,
    proportionOfJobs: 1667,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-7',
    name: '2-7',
    position: { x: 2, y: 7 },
    icon: Object.keys(iconPaths)[40+7],
    color: 'black',
    residents: 2589,
    proportionOfJobs: 1647,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-2',
    name: '6-2',
    position: { x: 6, y: 2 },
    icon: Object.keys(iconPaths)[120+2],
    color: 'black',
    residents: 2557,
    proportionOfJobs: 3180,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-9',
    name: '7-9',
    position: { x: 7, y: 9 },
    icon: Object.keys(iconPaths)[140+9],
    color: 'black',
    residents: 2517,
    proportionOfJobs: 5525,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-18',
    name: '11-18',
    position: { x: 11, y: 18 },
    icon: Object.keys(iconPaths)[220+18],
    color: 'black',
    residents: 2492,
    proportionOfJobs: 830,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '9-19',
    name: '9-19',
    position: { x: 9, y: 19 },
    icon: Object.keys(iconPaths)[180+19],
    color: 'black',
    residents: 2479,
    proportionOfJobs: 1372,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '18-8',
    name: '18-8',
    position: { x: 18, y: 8 },
    icon: Object.keys(iconPaths)[360+8],
    color: 'black',
    residents: 2443,
    proportionOfJobs: 867,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-17',
    name: '12-17',
    position: { x: 12, y: 17 },
    icon: Object.keys(iconPaths)[240+17],
    color: 'black',
    residents: 2405,
    proportionOfJobs: 3344,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-13',
    name: '11-13',
    position: { x: 11, y: 13 },
    icon: Object.keys(iconPaths)[220+13],
    color: 'black',
    residents: 2387,
    proportionOfJobs: 10040,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-15',
    name: '7-15',
    position: { x: 7, y: 15 },
    icon: Object.keys(iconPaths)[140+15],
    color: 'black',
    residents: 2377,
    proportionOfJobs: 311,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '9-16',
    name: '9-16',
    position: { x: 9, y: 16 },
    icon: Object.keys(iconPaths)[180+16],
    color: 'black',
    residents: 2362,
    proportionOfJobs: 453,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-5',
    name: '10-5',
    position: { x: 10, y: 5 },
    icon: Object.keys(iconPaths)[200+5],
    color: 'black',
    residents: 2359,
    proportionOfJobs: 1333,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-19',
    name: '7-19',
    position: { x: 7, y: 19 },
    icon: Object.keys(iconPaths)[140+19],
    color: 'black',
    residents: 2345,
    proportionOfJobs: 365,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '18-6',
    name: '18-6',
    position: { x: 18, y: 6 },
    icon: Object.keys(iconPaths)[360+6],
    color: 'black',
    residents: 2345,
    proportionOfJobs: 681,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-5',
    name: '13-5',
    position: { x: 13, y: 5 },
    icon: Object.keys(iconPaths)[260+5],
    color: 'black',
    residents: 2332,
    proportionOfJobs: 791,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-3',
    name: '7-3',
    position: { x: 7, y: 3 },
    icon: Object.keys(iconPaths)[140+3],
    color: 'black',
    residents: 2329,
    proportionOfJobs: 802,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-10',
    name: '13-10',
    position: { x: 13, y: 10 },
    icon: Object.keys(iconPaths)[260+10],
    color: 'black',
    residents: 2315,
    proportionOfJobs: 1749,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-0',
    name: '4-0',
    position: { x: 4, y: 0 },
    icon: Object.keys(iconPaths)[80+0],
    color: 'black',
    residents: 2305,
    proportionOfJobs: 1358,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-15',
    name: '6-15',
    position: { x: 6, y: 15 },
    icon: Object.keys(iconPaths)[120+15],
    color: 'black',
    residents: 2294,
    proportionOfJobs: 886,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-18',
    name: '4-18',
    position: { x: 4, y: 18 },
    icon: Object.keys(iconPaths)[80+18],
    color: 'black',
    residents: 2273,
    proportionOfJobs: 1956,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '8-4',
    name: '8-4',
    position: { x: 8, y: 4 },
    icon: Object.keys(iconPaths)[160+4],
    color: 'black',
    residents: 2264,
    proportionOfJobs: 1043,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-8',
    name: '12-8',
    position: { x: 12, y: 8 },
    icon: Object.keys(iconPaths)[240+8],
    color: 'black',
    residents: 2211,
    proportionOfJobs: 14211,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-2',
    name: '12-2',
    position: { x: 12, y: 2 },
    icon: Object.keys(iconPaths)[240+2],
    color: 'black',
    residents: 2192,
    proportionOfJobs: 329,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-19',
    name: '3-19',
    position: { x: 3, y: 19 },
    icon: Object.keys(iconPaths)[60+19],
    color: 'black',
    residents: 2176,
    proportionOfJobs: 546,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '18-5',
    name: '18-5',
    position: { x: 18, y: 5 },
    icon: Object.keys(iconPaths)[360+5],
    color: 'black',
    residents: 2171,
    proportionOfJobs: 16392,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-17',
    name: '7-17',
    position: { x: 7, y: 17 },
    icon: Object.keys(iconPaths)[140+17],
    color: 'black',
    residents: 2157,
    proportionOfJobs: 767,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-1',
    name: '11-1',
    position: { x: 11, y: 1 },
    icon: Object.keys(iconPaths)[220+1],
    color: 'black',
    residents: 2152,
    proportionOfJobs: 145,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '17-8',
    name: '17-8',
    position: { x: 17, y: 8 },
    icon: Object.keys(iconPaths)[340+8],
    color: 'black',
    residents: 2131,
    proportionOfJobs: 389,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-15',
    name: '2-15',
    position: { x: 2, y: 15 },
    icon: Object.keys(iconPaths)[40+15],
    color: 'black',
    residents: 2129,
    proportionOfJobs: 744,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '14-1',
    name: '14-1',
    position: { x: 14, y: 1 },
    icon: Object.keys(iconPaths)[280+1],
    color: 'black',
    residents: 2118,
    proportionOfJobs: 334,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '15-6',
    name: '15-6',
    position: { x: 15, y: 6 },
    icon: Object.keys(iconPaths)[300+6],
    color: 'black',
    residents: 2108,
    proportionOfJobs: 2281,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-10',
    name: '7-10',
    position: { x: 7, y: 10 },
    icon: Object.keys(iconPaths)[140+10],
    color: 'black',
    residents: 2093,
    proportionOfJobs: 1898,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-12',
    name: '7-12',
    position: { x: 7, y: 12 },
    icon: Object.keys(iconPaths)[140+12],
    color: 'black',
    residents: 2075,
    proportionOfJobs: 943,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '14-19',
    name: '14-19',
    position: { x: 14, y: 19 },
    icon: Object.keys(iconPaths)[280+19],
    color: 'black',
    residents: 2073,
    proportionOfJobs: 1010,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '19-14',
    name: '19-14',
    position: { x: 19, y: 14 },
    icon: Object.keys(iconPaths)[380+14],
    color: 'black',
    residents: 2064,
    proportionOfJobs: 654,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '8-3',
    name: '8-3',
    position: { x: 8, y: 3 },
    icon: Object.keys(iconPaths)[160+3],
    color: 'black',
    residents: 2060,
    proportionOfJobs: 374,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-12',
    name: '2-12',
    position: { x: 2, y: 12 },
    icon: Object.keys(iconPaths)[40+12],
    color: 'black',
    residents: 2042,
    proportionOfJobs: 4531,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-10',
    name: '11-10',
    position: { x: 11, y: 10 },
    icon: Object.keys(iconPaths)[220+10],
    color: 'black',
    residents: 2037,
    proportionOfJobs: 4209,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-3',
    name: '12-3',
    position: { x: 12, y: 3 },
    icon: Object.keys(iconPaths)[240+3],
    color: 'black',
    residents: 2036,
    proportionOfJobs: 450,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-2',
    name: '4-2',
    position: { x: 4, y: 2 },
    icon: Object.keys(iconPaths)[80+2],
    color: 'black',
    residents: 2035,
    proportionOfJobs: 833,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '8-1',
    name: '8-1',
    position: { x: 8, y: 1 },
    icon: Object.keys(iconPaths)[160+1],
    color: 'black',
    residents: 2032,
    proportionOfJobs: 82,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-4',
    name: '10-4',
    position: { x: 10, y: 4 },
    icon: Object.keys(iconPaths)[200+4],
    color: 'black',
    residents: 2028,
    proportionOfJobs: 435,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-18',
    name: '5-18',
    position: { x: 5, y: 18 },
    icon: Object.keys(iconPaths)[100+18],
    color: 'black',
    residents: 2011,
    proportionOfJobs: 261,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '9-2',
    name: '9-2',
    position: { x: 9, y: 2 },
    icon: Object.keys(iconPaths)[180+2],
    color: 'black',
    residents: 1999,
    proportionOfJobs: 236,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-11',
    name: '13-11',
    position: { x: 13, y: 11 },
    icon: Object.keys(iconPaths)[260+11],
    color: 'black',
    residents: 1995,
    proportionOfJobs: 1059,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '15-8',
    name: '15-8',
    position: { x: 15, y: 8 },
    icon: Object.keys(iconPaths)[300+8],
    color: 'black',
    residents: 1994,
    proportionOfJobs: 404,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-7',
    name: '11-7',
    position: { x: 11, y: 7 },
    icon: Object.keys(iconPaths)[220+7],
    color: 'black',
    residents: 1992,
    proportionOfJobs: 6121,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-16',
    name: '7-16',
    position: { x: 7, y: 16 },
    icon: Object.keys(iconPaths)[140+16],
    color: 'black',
    residents: 1979,
    proportionOfJobs: 1137,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-8',
    name: '10-8',
    position: { x: 10, y: 8 },
    icon: Object.keys(iconPaths)[200+8],
    color: 'black',
    residents: 1971,
    proportionOfJobs: 266,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-5',
    name: '12-5',
    position: { x: 12, y: 5 },
    icon: Object.keys(iconPaths)[240+5],
    color: 'black',
    residents: 1968,
    proportionOfJobs: 370,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-18',
    name: '6-18',
    position: { x: 6, y: 18 },
    icon: Object.keys(iconPaths)[120+18],
    color: 'black',
    residents: 1966,
    proportionOfJobs: 783,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-7',
    name: '13-7',
    position: { x: 13, y: 7 },
    icon: Object.keys(iconPaths)[260+7],
    color: 'black',
    residents: 1959,
    proportionOfJobs: 9682,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-3',
    name: '5-3',
    position: { x: 5, y: 3 },
    icon: Object.keys(iconPaths)[100+3],
    color: 'black',
    residents: 1902,
    proportionOfJobs: 5424,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '8-2',
    name: '8-2',
    position: { x: 8, y: 2 },
    icon: Object.keys(iconPaths)[160+2],
    color: 'black',
    residents: 1884,
    proportionOfJobs: 649,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-7',
    name: '12-7',
    position: { x: 12, y: 7 },
    icon: Object.keys(iconPaths)[240+7],
    color: 'black',
    residents: 1878,
    proportionOfJobs: 459,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-12',
    name: '11-12',
    position: { x: 11, y: 12 },
    icon: Object.keys(iconPaths)[220+12],
    color: 'black',
    residents: 1874,
    proportionOfJobs: 1126,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '15-0',
    name: '15-0',
    position: { x: 15, y: 0 },
    icon: Object.keys(iconPaths)[300+0],
    color: 'black',
    residents: 1865,
    proportionOfJobs: 365,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '17-7',
    name: '17-7',
    position: { x: 17, y: 7 },
    icon: Object.keys(iconPaths)[340+7],
    color: 'black',
    residents: 1862,
    proportionOfJobs: 649,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '4-19',
    name: '4-19',
    position: { x: 4, y: 19 },
    icon: Object.keys(iconPaths)[80+19],
    color: 'black',
    residents: 1853,
    proportionOfJobs: 667,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-2',
    name: '11-2',
    position: { x: 11, y: 2 },
    icon: Object.keys(iconPaths)[220+2],
    color: 'black',
    residents: 1825,
    proportionOfJobs: 405,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-6',
    name: '5-6',
    position: { x: 5, y: 6 },
    icon: Object.keys(iconPaths)[100+6],
    color: 'black',
    residents: 1822,
    proportionOfJobs: 44995,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-3',
    name: '2-3',
    position: { x: 2, y: 3 },
    icon: Object.keys(iconPaths)[40+3],
    color: 'black',
    residents: 1816,
    proportionOfJobs: 477,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-18',
    name: '3-18',
    position: { x: 3, y: 18 },
    icon: Object.keys(iconPaths)[60+18],
    color: 'black',
    residents: 1811,
    proportionOfJobs: 3294,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-4',
    name: '11-4',
    position: { x: 11, y: 4 },
    icon: Object.keys(iconPaths)[220+4],
    color: 'black',
    residents: 1803,
    proportionOfJobs: 517,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '17-16',
    name: '17-16',
    position: { x: 17, y: 16 },
    icon: Object.keys(iconPaths)[340+16],
    color: 'black',
    residents: 1769,
    proportionOfJobs: 421,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-9',
    name: '10-9',
    position: { x: 10, y: 9 },
    icon: Object.keys(iconPaths)[200+9],
    color: 'black',
    residents: 1765,
    proportionOfJobs: 516,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-1',
    name: '5-1',
    position: { x: 5, y: 1 },
    icon: Object.keys(iconPaths)[100+1],
    color: 'black',
    residents: 1737,
    proportionOfJobs: 179,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-10',
    name: '10-10',
    position: { x: 10, y: 10 },
    icon: Object.keys(iconPaths)[200+10],
    color: 'black',
    residents: 1734,
    proportionOfJobs: 1158,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-17',
    name: '6-17',
    position: { x: 6, y: 17 },
    icon: Object.keys(iconPaths)[120+17],
    color: 'black',
    residents: 1719,
    proportionOfJobs: 426,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '16-6',
    name: '16-6',
    position: { x: 16, y: 6 },
    icon: Object.keys(iconPaths)[320+6],
    color: 'black',
    residents: 1703,
    proportionOfJobs: 1392,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-12',
    name: '6-12',
    position: { x: 6, y: 12 },
    icon: Object.keys(iconPaths)[120+12],
    color: 'black',
    residents: 1682,
    proportionOfJobs: 1422,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '18-12',
    name: '18-12',
    position: { x: 18, y: 12 },
    icon: Object.keys(iconPaths)[360+12],
    color: 'black',
    residents: 1669,
    proportionOfJobs: 1577,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-16',
    name: '3-16',
    position: { x: 3, y: 16 },
    icon: Object.keys(iconPaths)[60+16],
    color: 'black',
    residents: 1627,
    proportionOfJobs: 310,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-0',
    name: '6-0',
    position: { x: 6, y: 0 },
    icon: Object.keys(iconPaths)[120+0],
    color: 'black',
    residents: 1623,
    proportionOfJobs: 833,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-9',
    name: '3-9',
    position: { x: 3, y: 9 },
    icon: Object.keys(iconPaths)[60+9],
    color: 'black',
    residents: 1620,
    proportionOfJobs: 6354,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '15-17',
    name: '15-17',
    position: { x: 15, y: 17 },
    icon: Object.keys(iconPaths)[300+17],
    color: 'black',
    residents: 1610,
    proportionOfJobs: 311,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-0',
    name: '11-0',
    position: { x: 11, y: 0 },
    icon: Object.keys(iconPaths)[220+0],
    color: 'black',
    residents: 1595,
    proportionOfJobs: 15141,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '9-3',
    name: '9-3',
    position: { x: 9, y: 3 },
    icon: Object.keys(iconPaths)[180+3],
    color: 'black',
    residents: 1589,
    proportionOfJobs: 641,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '3-17',
    name: '3-17',
    position: { x: 3, y: 17 },
    icon: Object.keys(iconPaths)[60+17],
    color: 'black',
    residents: 1560,
    proportionOfJobs: 232,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '15-10',
    name: '15-10',
    position: { x: 15, y: 10 },
    icon: Object.keys(iconPaths)[300+10],
    color: 'black',
    residents: 1534,
    proportionOfJobs: 484,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-19',
    name: '2-19',
    position: { x: 2, y: 19 },
    icon: Object.keys(iconPaths)[40+19],
    color: 'black',
    residents: 1494,
    proportionOfJobs: 415,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-11',
    name: '11-11',
    position: { x: 11, y: 11 },
    icon: Object.keys(iconPaths)[220+11],
    color: 'black',
    residents: 1487,
    proportionOfJobs: 8644,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '8-13',
    name: '8-13',
    position: { x: 8, y: 13 },
    icon: Object.keys(iconPaths)[160+13],
    color: 'black',
    residents: 1452,
    proportionOfJobs: 1472,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '8-16',
    name: '8-16',
    position: { x: 8, y: 16 },
    icon: Object.keys(iconPaths)[160+16],
    color: 'black',
    residents: 1434,
    proportionOfJobs: 550,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '2-1',
    name: '2-1',
    position: { x: 2, y: 1 },
    icon: Object.keys(iconPaths)[40+1],
    color: 'black',
    residents: 1400,
    proportionOfJobs: 89,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '10-6',
    name: '10-6',
    position: { x: 10, y: 6 },
    icon: Object.keys(iconPaths)[200+6],
    color: 'black',
    residents: 1390,
    proportionOfJobs: 1263,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '13-4',
    name: '13-4',
    position: { x: 13, y: 4 },
    icon: Object.keys(iconPaths)[260+4],
    color: 'black',
    residents: 1383,
    proportionOfJobs: 176,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '18-15',
    name: '18-15',
    position: { x: 18, y: 15 },
    icon: Object.keys(iconPaths)[360+15],
    color: 'black',
    residents: 1358,
    proportionOfJobs: 517,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '12-12',
    name: '12-12',
    position: { x: 12, y: 12 },
    icon: Object.keys(iconPaths)[240+12],
    color: 'black',
    residents: 1345,
    proportionOfJobs: 1430,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-0',
    name: '7-0',
    position: { x: 7, y: 0 },
    icon: Object.keys(iconPaths)[140+0],
    color: 'black',
    residents: 1317,
    proportionOfJobs: 10368,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '11-6',
    name: '11-6',
    position: { x: 11, y: 6 },
    icon: Object.keys(iconPaths)[220+6],
    color: 'black',
    residents: 1314,
    proportionOfJobs: 393,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '9-10',
    name: '9-10',
    position: { x: 9, y: 10 },
    icon: Object.keys(iconPaths)[180+10],
    color: 'black',
    residents: 1037,
    proportionOfJobs: 611,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '5-4',
    name: '5-4',
    position: { x: 5, y: 4 },
    icon: Object.keys(iconPaths)[100+4],
    color: 'black',
    residents: 1027,
    proportionOfJobs: 17963,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '7-1',
    name: '7-1',
    position: { x: 7, y: 1 },
    icon: Object.keys(iconPaths)[140+1],
    color: 'black',
    residents: 959,
    proportionOfJobs: 4459,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  },
  {
    id: '6-11',
    name: '6-11',
    position: { x: 6, y: 11 },
    icon: Object.keys(iconPaths)[120+11],
    color: 'black',
    residents: 526,
    proportionOfJobs: 25731,
    availableShifts: [],
    recreationalDemandCoefficient: 1,
  }
];

export default neighborhoods;
